# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0blogin.proto\"5\n\x10\x43reateAccountReq\x12\x0f\n\x07\x41\x63\x63ount\x18\x01 \x01(\t\x12\x10\n\x08Password\x18\x02 \x01(\t\"\x1f\n\rSelectRoleReq\x12\x0e\n\x06UserId\x18\x01 \x01(\x03\" \n\rSelectRoleAck\x12\x0f\n\x07\x45rrCode\x18\x01 \x01(\x05\"\x1f\n\rDeleteRoleReq\x12\x0e\n\x06UserId\x18\x01 \x01(\x03\" \n\rDeleteRoleAck\x12\x0f\n\x07\x45rrCode\x18\x01 \x01(\x05\";\n\x0bLoginAppAck\x12\x0f\n\x07\x45rrCode\x18\x01 \x01(\x05\x12\x1b\n\x08RoleList\x18\x02 \x03(\x0b\x32\t.RoleInfo\"4\n\x10\x43reateAccountAck\x12\r\n\x05Token\x18\x01 \x01(\t\x12\x11\n\tAccountId\x18\x02 \x01(\x03\"/\n\x0bLoginAppReq\x12\r\n\x05Token\x18\x01 \x01(\t\x12\x11\n\tAccountId\x18\x02 \x01(\x03\"H\n\rCreateRoleReq\x12\x11\n\tAccountId\x18\x01 \x01(\x03\x12\x12\n\nRoleConfId\x18\x02 \x01(\x05\x12\x10\n\x08RoleName\x18\x03 \x01(\t\"0\n\rCreateRoleAck\x12\x0f\n\x07\x45rrCode\x18\x01 \x01(\x05\x12\x0e\n\x06UserId\x18\x02 \x01(\x03\"T\n\x08RoleInfo\x12\x0e\n\x06UserId\x18\x01 \x01(\x03\x12\x13\n\x0bRoleImageId\x18\x02 \x01(\x05\x12\x10\n\x08RoleName\x18\x03 \x01(\t\x12\x11\n\tRoleLevel\x18\x04 \x01(\x05*\xae\x02\n\nLoginMsgId\x12\x10\n\x0cLogin_MSG_ID\x10\x00\x12\x1c\n\x17LOGIN_CREATEACCOUNT_REQ\x10\xcd\x08\x12\x19\n\x14LOGIN_SELECTROLE_REQ\x10\xd3\x08\x12\x19\n\x14LOGIN_SELECTROLE_ACK\x10\xd4\x08\x12\x19\n\x14LOGIN_DELETEROLE_REQ\x10\xd5\x08\x12\x19\n\x14LOGIN_DELETEROLE_ACK\x10\xd6\x08\x12\x17\n\x12LOGIN_LOGINAPP_ACK\x10\xd0\x08\x12\x1c\n\x17LOGIN_CREATEACCOUNT_ACK\x10\xce\x08\x12\x17\n\x12LOGIN_LOGINAPP_REQ\x10\xcf\x08\x12\x19\n\x14LOGIN_CREATEROLE_REQ\x10\xd1\x08\x12\x19\n\x14LOGIN_CREATEROLE_ACK\x10\xd2\x08\x62\x06proto3'
)

_LOGINMSGID = _descriptor.EnumDescriptor(
  name='LoginMsgId',
  full_name='LoginMsgId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Login_MSG_ID', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_CREATEACCOUNT_REQ', index=1, number=1101,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_SELECTROLE_REQ', index=2, number=1107,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_SELECTROLE_ACK', index=3, number=1108,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_DELETEROLE_REQ', index=4, number=1109,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_DELETEROLE_ACK', index=5, number=1110,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_LOGINAPP_ACK', index=6, number=1104,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_CREATEACCOUNT_ACK', index=7, number=1102,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_LOGINAPP_REQ', index=8, number=1103,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_CREATEROLE_REQ', index=9, number=1105,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOGIN_CREATEROLE_ACK', index=10, number=1106,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=579,
  serialized_end=881,
)
_sym_db.RegisterEnumDescriptor(_LOGINMSGID)

LoginMsgId = enum_type_wrapper.EnumTypeWrapper(_LOGINMSGID)
Login_MSG_ID = 0
LOGIN_CREATEACCOUNT_REQ = 1101
LOGIN_SELECTROLE_REQ = 1107
LOGIN_SELECTROLE_ACK = 1108
LOGIN_DELETEROLE_REQ = 1109
LOGIN_DELETEROLE_ACK = 1110
LOGIN_LOGINAPP_ACK = 1104
LOGIN_CREATEACCOUNT_ACK = 1102
LOGIN_LOGINAPP_REQ = 1103
LOGIN_CREATEROLE_REQ = 1105
LOGIN_CREATEROLE_ACK = 1106



_CREATEACCOUNTREQ = _descriptor.Descriptor(
  name='CreateAccountReq',
  full_name='CreateAccountReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Account', full_name='CreateAccountReq.Account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Password', full_name='CreateAccountReq.Password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=68,
)


_SELECTROLEREQ = _descriptor.Descriptor(
  name='SelectRoleReq',
  full_name='SelectRoleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserId', full_name='SelectRoleReq.UserId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=101,
)


_SELECTROLEACK = _descriptor.Descriptor(
  name='SelectRoleAck',
  full_name='SelectRoleAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrCode', full_name='SelectRoleAck.ErrCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=135,
)


_DELETEROLEREQ = _descriptor.Descriptor(
  name='DeleteRoleReq',
  full_name='DeleteRoleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserId', full_name='DeleteRoleReq.UserId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=168,
)


_DELETEROLEACK = _descriptor.Descriptor(
  name='DeleteRoleAck',
  full_name='DeleteRoleAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrCode', full_name='DeleteRoleAck.ErrCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=202,
)


_LOGINAPPACK = _descriptor.Descriptor(
  name='LoginAppAck',
  full_name='LoginAppAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrCode', full_name='LoginAppAck.ErrCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RoleList', full_name='LoginAppAck.RoleList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=263,
)


_CREATEACCOUNTACK = _descriptor.Descriptor(
  name='CreateAccountAck',
  full_name='CreateAccountAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Token', full_name='CreateAccountAck.Token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AccountId', full_name='CreateAccountAck.AccountId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=317,
)


_LOGINAPPREQ = _descriptor.Descriptor(
  name='LoginAppReq',
  full_name='LoginAppReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Token', full_name='LoginAppReq.Token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AccountId', full_name='LoginAppReq.AccountId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=366,
)


_CREATEROLEREQ = _descriptor.Descriptor(
  name='CreateRoleReq',
  full_name='CreateRoleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccountId', full_name='CreateRoleReq.AccountId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RoleConfId', full_name='CreateRoleReq.RoleConfId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RoleName', full_name='CreateRoleReq.RoleName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=440,
)


_CREATEROLEACK = _descriptor.Descriptor(
  name='CreateRoleAck',
  full_name='CreateRoleAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ErrCode', full_name='CreateRoleAck.ErrCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UserId', full_name='CreateRoleAck.UserId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=490,
)


_ROLEINFO = _descriptor.Descriptor(
  name='RoleInfo',
  full_name='RoleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserId', full_name='RoleInfo.UserId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RoleImageId', full_name='RoleInfo.RoleImageId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RoleName', full_name='RoleInfo.RoleName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RoleLevel', full_name='RoleInfo.RoleLevel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=576,
)

_LOGINAPPACK.fields_by_name['RoleList'].message_type = _ROLEINFO
DESCRIPTOR.message_types_by_name['CreateAccountReq'] = _CREATEACCOUNTREQ
DESCRIPTOR.message_types_by_name['SelectRoleReq'] = _SELECTROLEREQ
DESCRIPTOR.message_types_by_name['SelectRoleAck'] = _SELECTROLEACK
DESCRIPTOR.message_types_by_name['DeleteRoleReq'] = _DELETEROLEREQ
DESCRIPTOR.message_types_by_name['DeleteRoleAck'] = _DELETEROLEACK
DESCRIPTOR.message_types_by_name['LoginAppAck'] = _LOGINAPPACK
DESCRIPTOR.message_types_by_name['CreateAccountAck'] = _CREATEACCOUNTACK
DESCRIPTOR.message_types_by_name['LoginAppReq'] = _LOGINAPPREQ
DESCRIPTOR.message_types_by_name['CreateRoleReq'] = _CREATEROLEREQ
DESCRIPTOR.message_types_by_name['CreateRoleAck'] = _CREATEROLEACK
DESCRIPTOR.message_types_by_name['RoleInfo'] = _ROLEINFO
DESCRIPTOR.enum_types_by_name['LoginMsgId'] = _LOGINMSGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateAccountReq = _reflection.GeneratedProtocolMessageType('CreateAccountReq', (_message.Message,), {
  'DESCRIPTOR' : _CREATEACCOUNTREQ,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:CreateAccountReq)
  })
_sym_db.RegisterMessage(CreateAccountReq)

SelectRoleReq = _reflection.GeneratedProtocolMessageType('SelectRoleReq', (_message.Message,), {
  'DESCRIPTOR' : _SELECTROLEREQ,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:SelectRoleReq)
  })
_sym_db.RegisterMessage(SelectRoleReq)

SelectRoleAck = _reflection.GeneratedProtocolMessageType('SelectRoleAck', (_message.Message,), {
  'DESCRIPTOR' : _SELECTROLEACK,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:SelectRoleAck)
  })
_sym_db.RegisterMessage(SelectRoleAck)

DeleteRoleReq = _reflection.GeneratedProtocolMessageType('DeleteRoleReq', (_message.Message,), {
  'DESCRIPTOR' : _DELETEROLEREQ,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:DeleteRoleReq)
  })
_sym_db.RegisterMessage(DeleteRoleReq)

DeleteRoleAck = _reflection.GeneratedProtocolMessageType('DeleteRoleAck', (_message.Message,), {
  'DESCRIPTOR' : _DELETEROLEACK,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:DeleteRoleAck)
  })
_sym_db.RegisterMessage(DeleteRoleAck)

LoginAppAck = _reflection.GeneratedProtocolMessageType('LoginAppAck', (_message.Message,), {
  'DESCRIPTOR' : _LOGINAPPACK,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:LoginAppAck)
  })
_sym_db.RegisterMessage(LoginAppAck)

CreateAccountAck = _reflection.GeneratedProtocolMessageType('CreateAccountAck', (_message.Message,), {
  'DESCRIPTOR' : _CREATEACCOUNTACK,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:CreateAccountAck)
  })
_sym_db.RegisterMessage(CreateAccountAck)

LoginAppReq = _reflection.GeneratedProtocolMessageType('LoginAppReq', (_message.Message,), {
  'DESCRIPTOR' : _LOGINAPPREQ,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:LoginAppReq)
  })
_sym_db.RegisterMessage(LoginAppReq)

CreateRoleReq = _reflection.GeneratedProtocolMessageType('CreateRoleReq', (_message.Message,), {
  'DESCRIPTOR' : _CREATEROLEREQ,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:CreateRoleReq)
  })
_sym_db.RegisterMessage(CreateRoleReq)

CreateRoleAck = _reflection.GeneratedProtocolMessageType('CreateRoleAck', (_message.Message,), {
  'DESCRIPTOR' : _CREATEROLEACK,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:CreateRoleAck)
  })
_sym_db.RegisterMessage(CreateRoleAck)

RoleInfo = _reflection.GeneratedProtocolMessageType('RoleInfo', (_message.Message,), {
  'DESCRIPTOR' : _ROLEINFO,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:RoleInfo)
  })
_sym_db.RegisterMessage(RoleInfo)


# @@protoc_insertion_point(module_scope)
