# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../designer/ui/modify_proto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModifyProtoForm(object):
    def setupUi(self, ModifyProtoForm):
        ModifyProtoForm.setObjectName("ModifyProtoForm")
        ModifyProtoForm.resize(504, 544)
        self.tEtProtoDesc = QtWidgets.QTextEdit(ModifyProtoForm)
        self.tEtProtoDesc.setGeometry(QtCore.QRect(80, 90, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tEtProtoDesc.setFont(font)
        self.tEtProtoDesc.setObjectName("tEtProtoDesc")
        self.tEtProtoContent = QtWidgets.QTextEdit(ModifyProtoForm)
        self.tEtProtoContent.setGeometry(QtCore.QRect(10, 170, 481, 331))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tEtProtoContent.setFont(font)
        self.tEtProtoContent.setObjectName("tEtProtoContent")
        self.lEtProtoId = QtWidgets.QLineEdit(ModifyProtoForm)
        self.lEtProtoId.setGeometry(QtCore.QRect(80, 9, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lEtProtoId.setFont(font)
        self.lEtProtoId.setReadOnly(False)
        self.lEtProtoId.setObjectName("lEtProtoId")
        self.label_5 = QtWidgets.QLabel(ModifyProtoForm)
        self.label_5.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_5.setObjectName("label_5")
        self.bTnProtoModify = QtWidgets.QPushButton(ModifyProtoForm)
        self.bTnProtoModify.setGeometry(QtCore.QRect(280, 510, 75, 23))
        self.bTnProtoModify.setObjectName("bTnProtoModify")
        self.label_3 = QtWidgets.QLabel(ModifyProtoForm)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(ModifyProtoForm)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(ModifyProtoForm)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.label_6.setObjectName("label_6")
        self.lEtProtoName = QtWidgets.QLineEdit(ModifyProtoForm)
        self.lEtProtoName.setGeometry(QtCore.QRect(80, 49, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lEtProtoName.setFont(font)
        self.lEtProtoName.setObjectName("lEtProtoName")
        self.cBxProtocol = QtWidgets.QCheckBox(ModifyProtoForm)
        self.cBxProtocol.setGeometry(QtCore.QRect(80, 510, 121, 16))
        self.cBxProtocol.setObjectName("cBxProtocol")

        self.retranslateUi(ModifyProtoForm)
        QtCore.QMetaObject.connectSlotsByName(ModifyProtoForm)

    def retranslateUi(self, ModifyProtoForm):
        _translate = QtCore.QCoreApplication.translate
        ModifyProtoForm.setWindowTitle(_translate("ModifyProtoForm", "修改协议"))
        self.label_5.setText(_translate("ModifyProtoForm", "协议说明："))
        self.bTnProtoModify.setText(_translate("ModifyProtoForm", "修改"))
        self.label_3.setText(_translate("ModifyProtoForm", "协议编号："))
        self.label_4.setText(_translate("ModifyProtoForm", "协议名称："))
        self.label_6.setText(_translate("ModifyProtoForm", "协议内容："))
        self.cBxProtocol.setText(_translate("ModifyProtoForm", "仅导出服务器"))
