# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../designer/ui/proto_tool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GameToolWindow(object):
    def setupUi(self, GameToolWindow):
        GameToolWindow.setObjectName("GameToolWindow")
        GameToolWindow.resize(896, 785)
        self.centralwidget = QtWidgets.QWidget(GameToolWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 881, 741))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label_2.setObjectName("label_2")
        self.lEtProtoSearch = QtWidgets.QLineEdit(self.tab)
        self.lEtProtoSearch.setGeometry(QtCore.QRect(50, 10, 261, 21))
        self.lEtProtoSearch.setObjectName("lEtProtoSearch")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(320, 40, 541, 671))
        self.groupBox.setObjectName("groupBox")
        self.lEtProtoId = QtWidgets.QLineEdit(self.groupBox)
        self.lEtProtoId.setEnabled(True)
        self.lEtProtoId.setGeometry(QtCore.QRect(90, 30, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lEtProtoId.setFont(font)
        self.lEtProtoId.setReadOnly(True)
        self.lEtProtoId.setObjectName("lEtProtoId")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 71, 21))
        self.label_3.setObjectName("label_3")
        self.lEtProtoName = QtWidgets.QLineEdit(self.groupBox)
        self.lEtProtoName.setGeometry(QtCore.QRect(90, 69, 431, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lEtProtoName.setFont(font)
        self.lEtProtoName.setReadOnly(True)
        self.lEtProtoName.setObjectName("lEtProtoName")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 71, 21))
        self.label_6.setObjectName("label_6")
        self.tEtProtoContent = QtWidgets.QTextEdit(self.groupBox)
        self.tEtProtoContent.setGeometry(QtCore.QRect(20, 170, 501, 461))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tEtProtoContent.setFont(font)
        self.tEtProtoContent.setReadOnly(True)
        self.tEtProtoContent.setObjectName("tEtProtoContent")
        self.bTnProtoModify = QtWidgets.QPushButton(self.groupBox)
        self.bTnProtoModify.setGeometry(QtCore.QRect(260, 640, 75, 23))
        self.bTnProtoModify.setObjectName("bTnProtoModify")
        self.tEtProtoDesc = QtWidgets.QTextEdit(self.groupBox)
        self.tEtProtoDesc.setGeometry(QtCore.QRect(90, 110, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tEtProtoDesc.setFont(font)
        self.tEtProtoDesc.setReadOnly(True)
        self.tEtProtoDesc.setObjectName("tEtProtoDesc")
        self.tRvProtocol = QtWidgets.QTreeWidget(self.tab)
        self.tRvProtocol.setGeometry(QtCore.QRect(10, 40, 301, 671))
        self.tRvProtocol.setRootIsDecorated(True)
        self.tRvProtocol.setHeaderHidden(True)
        self.tRvProtocol.setObjectName("tRvProtocol")
        self.tRvProtocol.headerItem().setText(0, "1")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 41, 21))
        self.label.setObjectName("label")
        self.lEtEnumSearch = QtWidgets.QLineEdit(self.tab_2)
        self.lEtEnumSearch.setGeometry(QtCore.QRect(50, 10, 261, 21))
        self.lEtEnumSearch.setObjectName("lEtEnumSearch")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 40, 541, 671))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lEtEnumName = QtWidgets.QLineEdit(self.groupBox_2)
        self.lEtEnumName.setGeometry(QtCore.QRect(90, 50, 431, 31))
        self.lEtEnumName.setReadOnly(True)
        self.lEtEnumName.setObjectName("lEtEnumName")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 71, 21))
        self.label_7.setObjectName("label_7")
        self.lEtEnumDesc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lEtEnumDesc.setGeometry(QtCore.QRect(90, 90, 431, 31))
        self.lEtEnumDesc.setReadOnly(True)
        self.lEtEnumDesc.setObjectName("lEtEnumDesc")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 130, 71, 21))
        self.label_10.setObjectName("label_10")
        self.bTnEnumModify = QtWidgets.QPushButton(self.groupBox_2)
        self.bTnEnumModify.setGeometry(QtCore.QRect(250, 640, 75, 23))
        self.bTnEnumModify.setObjectName("bTnEnumModify")
        self.tBvEnum = QtWidgets.QTableWidget(self.groupBox_2)
        self.tBvEnum.setGeometry(QtCore.QRect(90, 130, 431, 491))
        self.tBvEnum.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tBvEnum.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tBvEnum.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tBvEnum.setColumnCount(3)
        self.tBvEnum.setObjectName("tBvEnum")
        self.tBvEnum.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tBvEnum.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tBvEnum.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tBvEnum.setHorizontalHeaderItem(2, item)
        self.tBvEnum.verticalHeader().setVisible(False)
        self.tBvEnum.verticalHeader().setDefaultSectionSize(35)
        self.tBvEnum.verticalHeader().setMinimumSectionSize(30)
        self.tBvEnum.verticalHeader().setSortIndicatorShown(False)
        self.tBvEnum.verticalHeader().setStretchLastSection(False)
        self.rBtnCom = QtWidgets.QRadioButton(self.groupBox_2)
        self.rBtnCom.setGeometry(QtCore.QRect(418, 20, 101, 21))
        self.rBtnCom.setObjectName("rBtnCom")
        self.rBtnServer = QtWidgets.QRadioButton(self.groupBox_2)
        self.rBtnServer.setGeometry(QtCore.QRect(100, 20, 89, 21))
        self.rBtnServer.setObjectName("rBtnServer")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label_11.setObjectName("label_11")
        self.rBtnClient = QtWidgets.QRadioButton(self.groupBox_2)
        self.rBtnClient.setGeometry(QtCore.QRect(260, 20, 89, 21))
        self.rBtnClient.setObjectName("rBtnClient")
        self.tRvEnum = QtWidgets.QTreeWidget(self.tab_2)
        self.tRvEnum.setGeometry(QtCore.QRect(10, 40, 301, 671))
        self.tRvEnum.setRootIsDecorated(True)
        self.tRvEnum.setHeaderHidden(True)
        self.tRvEnum.setObjectName("tRvEnum")
        self.tRvEnum.headerItem().setText(0, "1")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_9.setObjectName("label_9")
        self.tEtReq = QtWidgets.QTextEdit(self.tab_3)
        self.tEtReq.setGeometry(QtCore.QRect(10, 140, 861, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tEtReq.setFont(font)
        self.tEtReq.setObjectName("tEtReq")
        self.bTnSendMsg = QtWidgets.QPushButton(self.tab_3)
        self.bTnSendMsg.setGeometry(QtCore.QRect(740, 70, 121, 51))
        self.bTnSendMsg.setObjectName("bTnSendMsg")
        self.cBbxServAddr = QtWidgets.QComboBox(self.tab_3)
        self.cBbxServAddr.setGeometry(QtCore.QRect(90, 80, 191, 31))
        self.cBbxServAddr.setObjectName("cBbxServAddr")
        self.cBbxServAddr.addItem("")
        self.cBbxServAddr.addItem("")
        self.cBbxProto = QtWidgets.QComboBox(self.tab_3)
        self.cBbxProto.setGeometry(QtCore.QRect(560, 80, 161, 31))
        self.cBbxProto.setObjectName("cBbxProto")
        self.cBbxProto.addItem("")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(320, 80, 141, 31))
        self.label_12.setObjectName("label_12")
        self.bTnConn = QtWidgets.QPushButton(self.tab_3)
        self.bTnConn.setGeometry(QtCore.QRect(10, 10, 191, 51))
        self.bTnConn.setObjectName("bTnConn")
        self.bTnDisconn = QtWidgets.QPushButton(self.tab_3)
        self.bTnDisconn.setGeometry(QtCore.QRect(240, 10, 211, 51))
        self.bTnDisconn.setObjectName("bTnDisconn")
        self.tEtResp = QtWidgets.QTextEdit(self.tab_3)
        self.tEtResp.setGeometry(QtCore.QRect(10, 370, 861, 341))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tEtResp.setFont(font)
        self.tEtResp.setReadOnly(True)
        self.tEtResp.setObjectName("tEtResp")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(20, 120, 141, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(10, 350, 141, 16))
        self.label_14.setObjectName("label_14")
        self.cbBxMsgClass = QtWidgets.QComboBox(self.tab_3)
        self.cbBxMsgClass.setGeometry(QtCore.QRect(420, 81, 111, 31))
        self.cbBxMsgClass.setObjectName("cbBxMsgClass")
        self.cbBxMsgClass.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        self.btnExportPb = QtWidgets.QPushButton(self.centralwidget)
        self.btnExportPb.setGeometry(QtCore.QRect(560, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btnExportPb.setFont(font)
        self.btnExportPb.setAutoDefault(True)
        self.btnExportPb.setDefault(False)
        self.btnExportPb.setFlat(False)
        self.btnExportPb.setObjectName("btnExportPb")
        self.btnSetting = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetting.setGeometry(QtCore.QRect(820, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnSetting.setFont(font)
        self.btnSetting.setObjectName("btnSetting")
        self.btnExportEnum = QtWidgets.QPushButton(self.centralwidget)
        self.btnExportEnum.setGeometry(QtCore.QRect(650, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnExportEnum.setFont(font)
        self.btnExportEnum.setAutoDefault(True)
        self.btnExportEnum.setObjectName("btnExportEnum")
        self.btnExportTable = QtWidgets.QPushButton(self.centralwidget)
        self.btnExportTable.setGeometry(QtCore.QRect(730, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnExportTable.setFont(font)
        self.btnExportTable.setObjectName("btnExportTable")
        GameToolWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GameToolWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 896, 23))
        self.menubar.setObjectName("menubar")
        GameToolWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GameToolWindow)
        self.statusbar.setObjectName("statusbar")
        GameToolWindow.setStatusBar(self.statusbar)
        self.menuExportExcel = QtWidgets.QAction(GameToolWindow)
        self.menuExportExcel.setObjectName("menuExportExcel")
        self.menuExportPb = QtWidgets.QAction(GameToolWindow)
        self.menuExportPb.setObjectName("menuExportPb")
        self.menuExportClientPb = QtWidgets.QAction(GameToolWindow)
        self.menuExportClientPb.setObjectName("menuExportClientPb")
        self.menuSave = QtWidgets.QAction(GameToolWindow)
        self.menuSave.setObjectName("menuSave")
        self.menuExit = QtWidgets.QAction(GameToolWindow)
        self.menuExit.setObjectName("menuExit")
        self.menuOpenSetting = QtWidgets.QAction(GameToolWindow)
        self.menuOpenSetting.setObjectName("menuOpenSetting")
        self.menuExportProto = QtWidgets.QAction(GameToolWindow)
        self.menuExportProto.setObjectName("menuExportProto")

        self.retranslateUi(GameToolWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GameToolWindow)

    def retranslateUi(self, GameToolWindow):
        _translate = QtCore.QCoreApplication.translate
        GameToolWindow.setWindowTitle(_translate("GameToolWindow", "游戏开发工具"))
        self.label_2.setText(_translate("GameToolWindow", "搜索："))
        self.groupBox.setTitle(_translate("GameToolWindow", "详细信息"))
        self.label_3.setText(_translate("GameToolWindow", "协议编号："))
        self.label_4.setText(_translate("GameToolWindow", "协议名称："))
        self.label_5.setText(_translate("GameToolWindow", "协议说明："))
        self.label_6.setText(_translate("GameToolWindow", "协议内容："))
        self.bTnProtoModify.setText(_translate("GameToolWindow", "修改"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GameToolWindow", "协议管理器"))
        self.label.setText(_translate("GameToolWindow", "搜索："))
        self.groupBox_2.setTitle(_translate("GameToolWindow", "详细信息"))
        self.label_7.setText(_translate("GameToolWindow", "枚举名称："))
        self.label_8.setText(_translate("GameToolWindow", "枚举说明："))
        self.label_10.setText(_translate("GameToolWindow", "枚举字段："))
        self.bTnEnumModify.setText(_translate("GameToolWindow", "修改"))
        item = self.tBvEnum.horizontalHeaderItem(0)
        item.setText(_translate("GameToolWindow", "索引"))
        item = self.tBvEnum.horizontalHeaderItem(1)
        item.setText(_translate("GameToolWindow", "名称"))
        item = self.tBvEnum.horizontalHeaderItem(2)
        item.setText(_translate("GameToolWindow", "说明"))
        self.rBtnCom.setText(_translate("GameToolWindow", "共用"))
        self.rBtnServer.setText(_translate("GameToolWindow", "服务器"))
        self.label_11.setText(_translate("GameToolWindow", "枚举类型："))
        self.rBtnClient.setText(_translate("GameToolWindow", "客户端"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("GameToolWindow", "枚举管理器"))
        self.label_9.setText(_translate("GameToolWindow", "服务器地址："))
        self.bTnSendMsg.setText(_translate("GameToolWindow", "发送消息"))
        self.cBbxServAddr.setItemText(0, _translate("GameToolWindow", "192.168.50.251:10300"))
        self.cBbxServAddr.setItemText(1, _translate("GameToolWindow", "192.168.50.250:10300"))
        self.cBbxProto.setItemText(0, _translate("GameToolWindow", "UserLogin:7056"))
        self.label_12.setText(_translate("GameToolWindow", "选择发送协议："))
        self.bTnConn.setText(_translate("GameToolWindow", "连接到服务器"))
        self.bTnDisconn.setText(_translate("GameToolWindow", "断开服务器连接"))
        self.label_13.setText(_translate("GameToolWindow", "发送消息："))
        self.label_14.setText(_translate("GameToolWindow", "返回消息："))
        self.cbBxMsgClass.setItemText(0, _translate("GameToolWindow", "login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("GameToolWindow", "协议测试"))
        self.btnExportPb.setText(_translate("GameToolWindow", "导出pb协议"))
        self.btnSetting.setText(_translate("GameToolWindow", "设置"))
        self.btnExportEnum.setText(_translate("GameToolWindow", "导出枚举"))
        self.btnExportTable.setText(_translate("GameToolWindow", "导出配置表"))
        self.menuExportExcel.setText(_translate("GameToolWindow", "导出配置表"))
        self.menuExportPb.setText(_translate("GameToolWindow", "导出协议"))
        self.menuExportClientPb.setText(_translate("GameToolWindow", "导出客户端[pb]"))
        self.menuSave.setText(_translate("GameToolWindow", "保存"))
        self.menuExit.setText(_translate("GameToolWindow", "关闭"))
        self.menuOpenSetting.setText(_translate("GameToolWindow", "打开设置"))
        self.menuExportProto.setText(_translate("GameToolWindow", "导出proto"))

