# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../designer/ui/setting.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingForm(object):
    def setupUi(self, SettingForm):
        SettingForm.setObjectName("SettingForm")
        SettingForm.resize(509, 469)
        self.tabWidget = QtWidgets.QTabWidget(SettingForm)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 491, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.lEtProtocPath = QtWidgets.QLineEdit(self.tab_4)
        self.lEtProtocPath.setGeometry(QtCore.QRect(20, 30, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lEtProtocPath.setFont(font)
        self.lEtProtocPath.setReadOnly(True)
        self.lEtProtocPath.setObjectName("lEtProtocPath")
        self.label = QtWidgets.QLabel(self.tab_4)
        self.label.setGeometry(QtCore.QRect(20, 0, 191, 21))
        self.label.setObjectName("label")
        self.bTnProtoc = QtWidgets.QPushButton(self.tab_4)
        self.bTnProtoc.setGeometry(QtCore.QRect(370, 30, 75, 23))
        self.bTnProtoc.setObjectName("bTnProtoc")
        self.lEtProtoPath = QtWidgets.QLineEdit(self.tab_4)
        self.lEtProtoPath.setGeometry(QtCore.QRect(20, 90, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lEtProtoPath.setFont(font)
        self.lEtProtoPath.setReadOnly(False)
        self.lEtProtoPath.setObjectName("lEtProtoPath")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 191, 21))
        self.label_2.setObjectName("label_2")
        self.bTnProto = QtWidgets.QPushButton(self.tab_4)
        self.bTnProto.setGeometry(QtCore.QRect(370, 90, 75, 23))
        self.bTnProto.setObjectName("bTnProto")
        self.bTnTable = QtWidgets.QPushButton(self.tab_4)
        self.bTnTable.setGeometry(QtCore.QRect(370, 150, 75, 23))
        self.bTnTable.setObjectName("bTnTable")
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 191, 21))
        self.label_3.setObjectName("label_3")
        self.lEtTablePath = QtWidgets.QLineEdit(self.tab_4)
        self.lEtTablePath.setGeometry(QtCore.QRect(20, 150, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lEtTablePath.setFont(font)
        self.lEtTablePath.setReadOnly(False)
        self.lEtTablePath.setObjectName("lEtTablePath")
        self.label_4 = QtWidgets.QLabel(self.tab_4)
        self.label_4.setGeometry(QtCore.QRect(20, 305, 101, 21))
        self.label_4.setObjectName("label_4")
        self.tEtIPList = QtWidgets.QTextEdit(self.tab_4)
        self.tEtIPList.setGeometry(QtCore.QRect(20, 330, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tEtIPList.setFont(font)
        self.tEtIPList.setObjectName("tEtIPList")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 191, 21))
        self.label_5.setObjectName("label_5")
        self.btnServerJson = QtWidgets.QPushButton(self.tab_4)
        self.btnServerJson.setGeometry(QtCore.QRect(370, 210, 75, 23))
        self.btnServerJson.setObjectName("btnServerJson")
        self.letServerJsonPath = QtWidgets.QLineEdit(self.tab_4)
        self.letServerJsonPath.setGeometry(QtCore.QRect(20, 210, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.letServerJsonPath.setFont(font)
        self.letServerJsonPath.setReadOnly(False)
        self.letServerJsonPath.setObjectName("letServerJsonPath")
        self.letClientJsonPath = QtWidgets.QLineEdit(self.tab_4)
        self.letClientJsonPath.setGeometry(QtCore.QRect(20, 270, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.letClientJsonPath.setFont(font)
        self.letClientJsonPath.setReadOnly(False)
        self.letClientJsonPath.setObjectName("letClientJsonPath")
        self.btnClientJson = QtWidgets.QPushButton(self.tab_4)
        self.btnClientJson.setGeometry(QtCore.QRect(370, 270, 75, 23))
        self.btnClientJson.setObjectName("btnClientJson")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 191, 21))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.bTnProtoAddTmpl = QtWidgets.QPushButton(self.tab)
        self.bTnProtoAddTmpl.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.bTnProtoAddTmpl.setObjectName("bTnProtoAddTmpl")
        self.lWProto = QtWidgets.QListWidget(self.tab)
        self.lWProto.setGeometry(QtCore.QRect(10, 40, 471, 381))
        self.lWProto.setObjectName("lWProto")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.bTnEnumAddTmpl = QtWidgets.QPushButton(self.tab_2)
        self.bTnEnumAddTmpl.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.bTnEnumAddTmpl.setObjectName("bTnEnumAddTmpl")
        self.lWEnum = QtWidgets.QListWidget(self.tab_2)
        self.lWEnum.setGeometry(QtCore.QRect(10, 40, 471, 381))
        self.lWEnum.setObjectName("lWEnum")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.bTnTableAddTmpl = QtWidgets.QPushButton(self.tab_3)
        self.bTnTableAddTmpl.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.bTnTableAddTmpl.setObjectName("bTnTableAddTmpl")
        self.lWTable = QtWidgets.QListWidget(self.tab_3)
        self.lWTable.setGeometry(QtCore.QRect(10, 40, 471, 381))
        self.lWTable.setObjectName("lWTable")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(SettingForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingForm)

    def retranslateUi(self, SettingForm):
        _translate = QtCore.QCoreApplication.translate
        SettingForm.setWindowTitle(_translate("SettingForm", "设置"))
        self.label.setText(_translate("SettingForm", "protoc文件路径："))
        self.bTnProtoc.setText(_translate("SettingForm", "选择"))
        self.label_2.setText(_translate("SettingForm", "生成proto文件路径："))
        self.bTnProto.setText(_translate("SettingForm", "选择"))
        self.bTnTable.setText(_translate("SettingForm", "选择"))
        self.label_3.setText(_translate("SettingForm", "配置表文件路径："))
        self.label_4.setText(_translate("SettingForm", "添加服务器地址："))
        self.label_5.setText(_translate("SettingForm", "保存json路径[server]："))
        self.btnServerJson.setText(_translate("SettingForm", "选择"))
        self.btnClientJson.setText(_translate("SettingForm", "选择"))
        self.label_6.setText(_translate("SettingForm", "保存json路径[client]："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("SettingForm", "工具配置"))
        self.bTnProtoAddTmpl.setText(_translate("SettingForm", "添加模板"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingForm", "协议配置"))
        self.bTnEnumAddTmpl.setText(_translate("SettingForm", "添加模板"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SettingForm", "枚举配置"))
        self.bTnTableAddTmpl.setText(_translate("SettingForm", "添加模板"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SettingForm", "配置表配置"))

