# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/create_proto_dir.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateDirForm(object):
    def setupUi(self, CreateDirForm):
        CreateDirForm.setObjectName("CreateDirForm")
        CreateDirForm.setWindowModality(QtCore.Qt.ApplicationModal)
        CreateDirForm.resize(352, 260)
        CreateDirForm.setAutoFillBackground(True)
        self.label = QtWidgets.QLabel(CreateDirForm)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label.setObjectName("label")
        self.lEtProtoDirName = QtWidgets.QLineEdit(CreateDirForm)
        self.lEtProtoDirName.setGeometry(QtCore.QRect(90, 20, 241, 20))
        self.lEtProtoDirName.setObjectName("lEtProtoDirName")
        self.bTnCreateDir = QtWidgets.QPushButton(CreateDirForm)
        self.bTnCreateDir.setGeometry(QtCore.QRect(140, 230, 75, 23))
        self.bTnCreateDir.setObjectName("bTnCreateDir")
        self.label_3 = QtWidgets.QLabel(CreateDirForm)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_3.setObjectName("label_3")
        self.lEtProtoPackage = QtWidgets.QLineEdit(CreateDirForm)
        self.lEtProtoPackage.setGeometry(QtCore.QRect(150, 50, 181, 20))
        self.lEtProtoPackage.setObjectName("lEtProtoPackage")
        self.textEdit = QtWidgets.QTextEdit(CreateDirForm)
        self.textEdit.setGeometry(QtCore.QRect(20, 130, 311, 91))
        self.textEdit.setReadOnly(False)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(CreateDirForm)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(CreateDirForm)
        self.comboBox.setGeometry(QtCore.QRect(20, 100, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(CreateDirForm)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 100, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(CreateDirForm)
        self.pushButton.setGeometry(QtCore.QRect(140, 100, 101, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(CreateDirForm)
        QtCore.QMetaObject.connectSlotsByName(CreateDirForm)

    def retranslateUi(self, CreateDirForm):
        _translate = QtCore.QCoreApplication.translate
        CreateDirForm.setWindowTitle(_translate("CreateDirForm", "创建目录"))
        self.label.setText(_translate("CreateDirForm", "目录名称："))
        self.bTnCreateDir.setText(_translate("CreateDirForm", "创建"))
        self.label_3.setText(_translate("CreateDirForm", "包名【proto package】"))
        self.lEtProtoPackage.setText(_translate("CreateDirForm", "*可以不填写*"))
        self.label_2.setText(_translate("CreateDirForm", "引入其他模块包【proto import】"))
        self.comboBox.setItemText(0, _translate("CreateDirForm", "game.common"))
        self.pushButton_2.setText(_translate("CreateDirForm", "清除文本"))
        self.pushButton.setText(_translate("CreateDirForm", "加入引入包"))
