# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/modify_proto_dir.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModifyDirForm(object):
    def setupUi(self, ModifyDirForm):
        ModifyDirForm.setObjectName("ModifyDirForm")
        ModifyDirForm.resize(352, 258)
        self.bTnAdd = QtWidgets.QPushButton(ModifyDirForm)
        self.bTnAdd.setGeometry(QtCore.QRect(140, 100, 101, 23))
        self.bTnAdd.setObjectName("bTnAdd")
        self.bTnModifyDir = QtWidgets.QPushButton(ModifyDirForm)
        self.bTnModifyDir.setGeometry(QtCore.QRect(140, 230, 75, 23))
        self.bTnModifyDir.setObjectName("bTnModifyDir")
        self.label_3 = QtWidgets.QLabel(ModifyDirForm)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 151, 16))
        self.label_3.setObjectName("label_3")
        self.lEtProtoPackage = QtWidgets.QLineEdit(ModifyDirForm)
        self.lEtProtoPackage.setGeometry(QtCore.QRect(150, 50, 181, 20))
        self.lEtProtoPackage.setObjectName("lEtProtoPackage")
        self.label_2 = QtWidgets.QLabel(ModifyDirForm)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.label_2.setObjectName("label_2")
        self.bTnClear = QtWidgets.QPushButton(ModifyDirForm)
        self.bTnClear.setGeometry(QtCore.QRect(250, 100, 81, 23))
        self.bTnClear.setObjectName("bTnClear")
        self.label = QtWidgets.QLabel(ModifyDirForm)
        self.label.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.label.setObjectName("label")
        self.cBbxPackage = QtWidgets.QComboBox(ModifyDirForm)
        self.cBbxPackage.setGeometry(QtCore.QRect(20, 100, 111, 22))
        self.cBbxPackage.setObjectName("cBbxPackage")
        self.cBbxPackage.addItem("")
        self.tEtPackage = QtWidgets.QTextEdit(ModifyDirForm)
        self.tEtPackage.setGeometry(QtCore.QRect(20, 130, 311, 91))
        self.tEtPackage.setReadOnly(False)
        self.tEtPackage.setObjectName("tEtPackage")
        self.lEtProtoDirName = QtWidgets.QLineEdit(ModifyDirForm)
        self.lEtProtoDirName.setGeometry(QtCore.QRect(90, 20, 241, 20))
        self.lEtProtoDirName.setObjectName("lEtProtoDirName")

        self.retranslateUi(ModifyDirForm)
        QtCore.QMetaObject.connectSlotsByName(ModifyDirForm)

    def retranslateUi(self, ModifyDirForm):
        _translate = QtCore.QCoreApplication.translate
        ModifyDirForm.setWindowTitle(_translate("ModifyDirForm", "修改目录"))
        self.bTnAdd.setText(_translate("ModifyDirForm", "加入引入包"))
        self.bTnModifyDir.setText(_translate("ModifyDirForm", "修改"))
        self.label_3.setText(_translate("ModifyDirForm", "包名【proto package】"))
        self.lEtProtoPackage.setText(_translate("ModifyDirForm", "*可以不填写*"))
        self.label_2.setText(_translate("ModifyDirForm", "引入其他模块包【proto import】"))
        self.bTnClear.setText(_translate("ModifyDirForm", "清除文本"))
        self.label.setText(_translate("ModifyDirForm", "目录名称："))
        self.cBbxPackage.setItemText(0, _translate("ModifyDirForm", "game.common"))
