// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameMsgId int32

const (
	GameMsgId_MSG_ID                GameMsgId = 0
	GameMsgId_GAME_ENTERGAMEREQ_REQ GameMsgId = 2001
	GameMsgId_GAME_ENTERGAMEACK_ACK GameMsgId = 2002
)

var GameMsgId_name = map[int32]string{
	0:    "MSG_ID",
	2001: "GAME_ENTERGAMEREQ_REQ",
	2002: "GAME_ENTERGAMEACK_ACK",
}

var GameMsgId_value = map[string]int32{
	"MSG_ID":                0,
	"GAME_ENTERGAMEREQ_REQ": 2001,
	"GAME_ENTERGAMEACK_ACK": 2002,
}

func (x GameMsgId) String() string {
	return proto.EnumName(GameMsgId_name, int32(x))
}

func (GameMsgId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

// 客户端请求进入游戏
type EnterGameReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	RoleId               int32    `protobuf:"varint,2,opt,name=RoleId,proto3" json:"RoleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGameReq) Reset()         { *m = EnterGameReq{} }
func (m *EnterGameReq) String() string { return proto.CompactTextString(m) }
func (*EnterGameReq) ProtoMessage()    {}
func (*EnterGameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *EnterGameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameReq.Unmarshal(m, b)
}
func (m *EnterGameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameReq.Marshal(b, m, deterministic)
}
func (m *EnterGameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameReq.Merge(m, src)
}
func (m *EnterGameReq) XXX_Size() int {
	return xxx_messageInfo_EnterGameReq.Size(m)
}
func (m *EnterGameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameReq proto.InternalMessageInfo

func (m *EnterGameReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *EnterGameReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

//
type EnterGameAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGameAck) Reset()         { *m = EnterGameAck{} }
func (m *EnterGameAck) String() string { return proto.CompactTextString(m) }
func (*EnterGameAck) ProtoMessage()    {}
func (*EnterGameAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *EnterGameAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameAck.Unmarshal(m, b)
}
func (m *EnterGameAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameAck.Marshal(b, m, deterministic)
}
func (m *EnterGameAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameAck.Merge(m, src)
}
func (m *EnterGameAck) XXX_Size() int {
	return xxx_messageInfo_EnterGameAck.Size(m)
}
func (m *EnterGameAck) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameAck.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameAck proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("GameMsgId", GameMsgId_name, GameMsgId_value)
	proto.RegisterType((*EnterGameReq)(nil), "EnterGameReq")
	proto.RegisterType((*EnterGameAck)(nil), "EnterGameAck")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe3, 0xe2, 0x71, 0xcd, 0x2b, 0x49, 0x2d, 0x72,
	0x4f, 0xcc, 0x4d, 0x0d, 0x4a, 0x2d, 0x14, 0x12, 0xe3, 0x62, 0x0b, 0x2d, 0x4e, 0x2d, 0xf2, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0xf2, 0x40, 0xe2, 0x41, 0xf9, 0x39, 0xa9, 0x9e,
	0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x50, 0x9e, 0x12, 0x1f, 0x92, 0x7e, 0xc7, 0xe4,
	0x6c, 0x2d, 0x7f, 0x2e, 0x4e, 0x10, 0xd3, 0xb7, 0x38, 0xdd, 0x33, 0x45, 0x88, 0x8b, 0x8b, 0xcd,
	0x37, 0xd8, 0x3d, 0xde, 0xd3, 0x45, 0x80, 0x41, 0x48, 0x8a, 0x4b, 0xd4, 0xdd, 0xd1, 0xd7, 0x35,
	0xde, 0xd5, 0x2f, 0xc4, 0x35, 0x08, 0xc4, 0x0a, 0x72, 0x0d, 0x8c, 0x0f, 0x72, 0x0d, 0x14, 0xb8,
	0xc8, 0x8f, 0x29, 0xe7, 0xe8, 0xec, 0x1d, 0xef, 0xe8, 0xec, 0x2d, 0x70, 0x89, 0x3f, 0x89, 0x0d,
	0xec, 0x4e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x74, 0xdb, 0xd6, 0xb5, 0x00, 0x00,
	0x00,
}
