// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameMsgId int32

const (
	GameMsgId_Game_MSG_ID        GameMsgId = 0
	GameMsgId_GAME_ENTERGAME_ACK GameMsgId = 2002
	GameMsgId_GAME_ENTERGAME_REQ GameMsgId = 2001
)

var GameMsgId_name = map[int32]string{
	0:    "Game_MSG_ID",
	2002: "GAME_ENTERGAME_ACK",
	2001: "GAME_ENTERGAME_REQ",
}

var GameMsgId_value = map[string]int32{
	"Game_MSG_ID":        0,
	"GAME_ENTERGAME_ACK": 2002,
	"GAME_ENTERGAME_REQ": 2001,
}

func (x GameMsgId) String() string {
	return proto.EnumName(GameMsgId_name, int32(x))
}

func (GameMsgId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

//
type EnterGameAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGameAck) Reset()         { *m = EnterGameAck{} }
func (m *EnterGameAck) String() string { return proto.CompactTextString(m) }
func (*EnterGameAck) ProtoMessage()    {}
func (*EnterGameAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *EnterGameAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameAck.Unmarshal(m, b)
}
func (m *EnterGameAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameAck.Marshal(b, m, deterministic)
}
func (m *EnterGameAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameAck.Merge(m, src)
}
func (m *EnterGameAck) XXX_Size() int {
	return xxx_messageInfo_EnterGameAck.Size(m)
}
func (m *EnterGameAck) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameAck.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameAck proto.InternalMessageInfo

// 客户端请求进入游戏
type EnterGameReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterGameReq) Reset()         { *m = EnterGameReq{} }
func (m *EnterGameReq) String() string { return proto.CompactTextString(m) }
func (*EnterGameReq) ProtoMessage()    {}
func (*EnterGameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *EnterGameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterGameReq.Unmarshal(m, b)
}
func (m *EnterGameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterGameReq.Marshal(b, m, deterministic)
}
func (m *EnterGameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterGameReq.Merge(m, src)
}
func (m *EnterGameReq) XXX_Size() int {
	return xxx_messageInfo_EnterGameReq.Size(m)
}
func (m *EnterGameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterGameReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnterGameReq proto.InternalMessageInfo

func (m *EnterGameReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterEnum("GameMsgId", GameMsgId_name, GameMsgId_value)
	proto.RegisterType((*EnterGameAck)(nil), "EnterGameAck")
	proto.RegisterType((*EnterGameReq)(nil), "EnterGameReq")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xe2, 0xe3, 0xe2, 0x71, 0xcd, 0x2b, 0x49, 0x2d, 0x72,
	0x4f, 0xcc, 0x4d, 0x75, 0x4c, 0xce, 0x56, 0x52, 0x43, 0xe2, 0x07, 0xa5, 0x16, 0x0a, 0x89, 0x71,
	0xb1, 0x85, 0x16, 0xa7, 0x16, 0x79, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41, 0x79,
	0x5a, 0x7e, 0x5c, 0x9c, 0x20, 0x25, 0xbe, 0xc5, 0xe9, 0x9e, 0x29, 0x42, 0xfc, 0x5c, 0xdc, 0x20,
	0x4e, 0xbc, 0x6f, 0xb0, 0x7b, 0xbc, 0xa7, 0x8b, 0x00, 0x83, 0x90, 0x38, 0x97, 0x90, 0xbb, 0xa3,
	0xaf, 0x6b, 0xbc, 0xab, 0x5f, 0x88, 0x6b, 0x10, 0x98, 0xe5, 0xe8, 0xec, 0x2d, 0x70, 0x89, 0x1f,
	0x8b, 0x44, 0x90, 0x6b, 0xa0, 0xc0, 0x45, 0xfe, 0x24, 0x36, 0xb0, 0x73, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x9f, 0xac, 0xeb, 0xdb, 0x9c, 0x00, 0x00, 0x00,
}
