// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginMsgId int32

const (
	LoginMsgId_MSG_ID                     LoginMsgId = 0
	LoginMsgId_LOGIN_LOGINREQ_REQ         LoginMsgId = 1103
	LoginMsgId_LOGIN_LOGINACK_ACK         LoginMsgId = 1104
	LoginMsgId_LOGIN_CREATEACCOUNTREQ_REQ LoginMsgId = 1101
	LoginMsgId_LOGIN_CREATEACCOUNTACK_ACK LoginMsgId = 1102
)

var LoginMsgId_name = map[int32]string{
	0:    "MSG_ID",
	1103: "LOGIN_LOGINREQ_REQ",
	1104: "LOGIN_LOGINACK_ACK",
	1101: "LOGIN_CREATEACCOUNTREQ_REQ",
	1102: "LOGIN_CREATEACCOUNTACK_ACK",
}

var LoginMsgId_value = map[string]int32{
	"MSG_ID":                     0,
	"LOGIN_LOGINREQ_REQ":         1103,
	"LOGIN_LOGINACK_ACK":         1104,
	"LOGIN_CREATEACCOUNTREQ_REQ": 1101,
	"LOGIN_CREATEACCOUNTACK_ACK": 1102,
}

func (x LoginMsgId) String() string {
	return proto.EnumName(LoginMsgId_name, int32(x))
}

func (LoginMsgId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

// 客户端请求登录到游戏中
type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 服务器返回请求登录信息
type LoginAck struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAck) Reset()         { *m = LoginAck{} }
func (m *LoginAck) String() string { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()    {}
func (*LoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAck.Unmarshal(m, b)
}
func (m *LoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAck.Marshal(b, m, deterministic)
}
func (m *LoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAck.Merge(m, src)
}
func (m *LoginAck) XXX_Size() int {
	return xxx_messageInfo_LoginAck.Size(m)
}
func (m *LoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAck proto.InternalMessageInfo

func (m *LoginAck) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginAck) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// 客户端请求创建账号
type CreateAccountReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountReq) Reset()         { *m = CreateAccountReq{} }
func (m *CreateAccountReq) String() string { return proto.CompactTextString(m) }
func (*CreateAccountReq) ProtoMessage()    {}
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *CreateAccountReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountReq.Unmarshal(m, b)
}
func (m *CreateAccountReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountReq.Marshal(b, m, deterministic)
}
func (m *CreateAccountReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountReq.Merge(m, src)
}
func (m *CreateAccountReq) XXX_Size() int {
	return xxx_messageInfo_CreateAccountReq.Size(m)
}
func (m *CreateAccountReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountReq proto.InternalMessageInfo

func (m *CreateAccountReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CreateAccountReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 创建账号返回
type CreateAccountAck struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountAck) Reset()         { *m = CreateAccountAck{} }
func (m *CreateAccountAck) String() string { return proto.CompactTextString(m) }
func (*CreateAccountAck) ProtoMessage()    {}
func (*CreateAccountAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *CreateAccountAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountAck.Unmarshal(m, b)
}
func (m *CreateAccountAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountAck.Marshal(b, m, deterministic)
}
func (m *CreateAccountAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountAck.Merge(m, src)
}
func (m *CreateAccountAck) XXX_Size() int {
	return xxx_messageInfo_CreateAccountAck.Size(m)
}
func (m *CreateAccountAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountAck.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountAck proto.InternalMessageInfo

func (m *CreateAccountAck) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateAccountAck) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterEnum("LoginMsgId", LoginMsgId_name, LoginMsgId_value)
	proto.RegisterType((*LoginReq)(nil), "loginReq")
	proto.RegisterType((*LoginAck)(nil), "loginAck")
	proto.RegisterType((*CreateAccountReq)(nil), "CreateAccountReq")
	proto.RegisterType((*CreateAccountAck)(nil), "CreateAccountAck")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe2, 0xe2, 0x00, 0x73, 0x83, 0x52, 0x0b,
	0x85, 0x24, 0xb8, 0xd8, 0x13, 0x93, 0x93, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x60, 0x5c, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xfc, 0xec, 0xd4, 0x3c, 0x09, 0x26, 0xb0,
	0x38, 0x84, 0xa3, 0x64, 0x0b, 0xd5, 0xeb, 0x98, 0x9c, 0x2d, 0x24, 0xce, 0xc5, 0x5e, 0x5a, 0x9c,
	0x5a, 0x14, 0x9f, 0x99, 0x02, 0xd6, 0xcb, 0x1a, 0xc4, 0x06, 0xe2, 0x7a, 0xa6, 0x20, 0x1b, 0xca,
	0x84, 0x62, 0xa8, 0x92, 0x07, 0x97, 0x80, 0x73, 0x51, 0x6a, 0x62, 0x49, 0xaa, 0x23, 0x44, 0x00,
	0xbf, 0x13, 0xa4, 0xb8, 0x38, 0x0a, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0xa0, 0x06, 0xc1,
	0xf9, 0x4a, 0x8e, 0x68, 0x26, 0xe1, 0x75, 0x10, 0x56, 0xbf, 0x68, 0xf5, 0x30, 0x72, 0x71, 0xf9,
	0x80, 0x3c, 0xe3, 0x5b, 0x9c, 0xee, 0x99, 0x22, 0xc4, 0xc5, 0xc5, 0xe6, 0x1b, 0xec, 0x1e, 0xef,
	0xe9, 0x22, 0xc0, 0x20, 0x24, 0xce, 0x25, 0xe4, 0xe3, 0xef, 0xee, 0xe9, 0x17, 0x0f, 0x26, 0x83,
	0x5c, 0x03, 0xe3, 0x83, 0x5c, 0x03, 0x05, 0xce, 0x73, 0xa0, 0x49, 0x38, 0x3a, 0x7b, 0xc7, 0x3b,
	0x3a, 0x7b, 0x0b, 0x5c, 0xe0, 0x10, 0x92, 0xe7, 0x92, 0x82, 0x48, 0x38, 0x07, 0xb9, 0x3a, 0x86,
	0xb8, 0x3a, 0x3a, 0x3b, 0xfb, 0x87, 0xfa, 0x85, 0xc0, 0x74, 0x9e, 0xc5, 0xa5, 0x00, 0x66, 0xc2,
	0x39, 0x8e, 0x24, 0x36, 0x70, 0xec, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x61, 0x81,
	0xa6, 0xac, 0x01, 0x00, 0x00,
}
