// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRoleAck_RET_TYPE int32

const (
	CreateRoleAck_RESULT_TYPE_SUCC         CreateRoleAck_RET_TYPE = 0
	CreateRoleAck_RESULT_TYPE_NO_SPACE     CreateRoleAck_RET_TYPE = 1
	CreateRoleAck_RESULT_TYPE_EXIST_NAME   CreateRoleAck_RET_TYPE = 2
	CreateRoleAck_RESULT_TYPE_NAME_INVALID CreateRoleAck_RET_TYPE = 3
	CreateRoleAck_RESULT_TYPE_SERVER_LIMIT CreateRoleAck_RET_TYPE = 4
)

var CreateRoleAck_RET_TYPE_name = map[int32]string{
	0: "RESULT_TYPE_SUCC",
	1: "RESULT_TYPE_NO_SPACE",
	2: "RESULT_TYPE_EXIST_NAME",
	3: "RESULT_TYPE_NAME_INVALID",
	4: "RESULT_TYPE_SERVER_LIMIT",
}

var CreateRoleAck_RET_TYPE_value = map[string]int32{
	"RESULT_TYPE_SUCC":         0,
	"RESULT_TYPE_NO_SPACE":     1,
	"RESULT_TYPE_EXIST_NAME":   2,
	"RESULT_TYPE_NAME_INVALID": 3,
	"RESULT_TYPE_SERVER_LIMIT": 4,
}

func (x CreateRoleAck_RET_TYPE) String() string {
	return proto.EnumName(CreateRoleAck_RET_TYPE_name, int32(x))
}

func (CreateRoleAck_RET_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3, 0}
}

type RoleListNotify_LoginAckCode int32

const (
	RoleListNotify_LOGIN_RESULT_SUC        RoleListNotify_LoginAckCode = 0
	RoleListNotify_LOGIN_NO_THREAD         RoleListNotify_LoginAckCode = 1100
	RoleListNotify_LOGIN_SERVER_ERROR      RoleListNotify_LoginAckCode = 1102
	RoleListNotify_LOGIN_RESULT_EXIST      RoleListNotify_LoginAckCode = 1103
	RoleListNotify_LOGIN_SCENE_NOT_EXIST   RoleListNotify_LoginAckCode = 1104
	RoleListNotify_LOGIN_RESULT_NO_GATEWAY RoleListNotify_LoginAckCode = 1105
	RoleListNotify_LOGIN_RESULT_NO_ROLE    RoleListNotify_LoginAckCode = 1106
	RoleListNotify_LOGIN_THREAD_BUSY       RoleListNotify_LoginAckCode = 1107
	RoleListNotify_LOGIN_LOGIN_FORBID      RoleListNotify_LoginAckCode = 1108
	RoleListNotify_LOGIN_ANTI_WALLOW       RoleListNotify_LoginAckCode = 1109
)

var RoleListNotify_LoginAckCode_name = map[int32]string{
	0:    "LOGIN_RESULT_SUC",
	1100: "LOGIN_NO_THREAD",
	1102: "LOGIN_SERVER_ERROR",
	1103: "LOGIN_RESULT_EXIST",
	1104: "LOGIN_SCENE_NOT_EXIST",
	1105: "LOGIN_RESULT_NO_GATEWAY",
	1106: "LOGIN_RESULT_NO_ROLE",
	1107: "LOGIN_THREAD_BUSY",
	1108: "LOGIN_LOGIN_FORBID",
	1109: "LOGIN_ANTI_WALLOW",
}

var RoleListNotify_LoginAckCode_value = map[string]int32{
	"LOGIN_RESULT_SUC":        0,
	"LOGIN_NO_THREAD":         1100,
	"LOGIN_SERVER_ERROR":      1102,
	"LOGIN_RESULT_EXIST":      1103,
	"LOGIN_SCENE_NOT_EXIST":   1104,
	"LOGIN_RESULT_NO_GATEWAY": 1105,
	"LOGIN_RESULT_NO_ROLE":    1106,
	"LOGIN_THREAD_BUSY":       1107,
	"LOGIN_LOGIN_FORBID":      1108,
	"LOGIN_ANTI_WALLOW":       1109,
}

func (x RoleListNotify_LoginAckCode) String() string {
	return proto.EnumName(RoleListNotify_LoginAckCode_name, int32(x))
}

func (RoleListNotify_LoginAckCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{6, 0}
}

// 界面上选中某个角色进入游戏
type RoleLoginReq struct {
	Accout               string   `protobuf:"bytes,1,opt,name=accout,proto3" json:"accout,omitempty"`
	RoleId               int32    `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleLoginReq) Reset()         { *m = RoleLoginReq{} }
func (m *RoleLoginReq) String() string { return proto.CompactTextString(m) }
func (*RoleLoginReq) ProtoMessage()    {}
func (*RoleLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *RoleLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleLoginReq.Unmarshal(m, b)
}
func (m *RoleLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleLoginReq.Marshal(b, m, deterministic)
}
func (m *RoleLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleLoginReq.Merge(m, src)
}
func (m *RoleLoginReq) XXX_Size() int {
	return xxx_messageInfo_RoleLoginReq.Size(m)
}
func (m *RoleLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleLoginReq proto.InternalMessageInfo

func (m *RoleLoginReq) GetAccout() string {
	if m != nil {
		return m.Accout
	}
	return ""
}

func (m *RoleLoginReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleLoginReq) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

// 角色进入游戏返回消息
type RoleLoginAck struct {
	Accout               string   `protobuf:"bytes,1,opt,name=accout,proto3" json:"accout,omitempty"`
	RoleId               int32    `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	SceneId              int32    `protobuf:"varint,4,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	LastSceneId          int32    `protobuf:"varint,5,opt,name=last_scene_id,json=lastSceneId,proto3" json:"last_scene_id,omitempty"`
	GwHostname           string   `protobuf:"bytes,6,opt,name=gw_hostname,json=gwHostname,proto3" json:"gw_hostname,omitempty"`
	GwPort               int32    `protobuf:"varint,7,opt,name=gw_port,json=gwPort,proto3" json:"gw_port,omitempty"`
	GsIndex              int32    `protobuf:"varint,8,opt,name=gs_index,json=gsIndex,proto3" json:"gs_index,omitempty"`
	ServerTime           int64    `protobuf:"varint,9,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	SessionKey           string   `protobuf:"bytes,10,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	Result               int32    `protobuf:"varint,11,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleLoginAck) Reset()         { *m = RoleLoginAck{} }
func (m *RoleLoginAck) String() string { return proto.CompactTextString(m) }
func (*RoleLoginAck) ProtoMessage()    {}
func (*RoleLoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *RoleLoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleLoginAck.Unmarshal(m, b)
}
func (m *RoleLoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleLoginAck.Marshal(b, m, deterministic)
}
func (m *RoleLoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleLoginAck.Merge(m, src)
}
func (m *RoleLoginAck) XXX_Size() int {
	return xxx_messageInfo_RoleLoginAck.Size(m)
}
func (m *RoleLoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleLoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_RoleLoginAck proto.InternalMessageInfo

func (m *RoleLoginAck) GetAccout() string {
	if m != nil {
		return m.Accout
	}
	return ""
}

func (m *RoleLoginAck) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleLoginAck) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *RoleLoginAck) GetSceneId() int32 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *RoleLoginAck) GetLastSceneId() int32 {
	if m != nil {
		return m.LastSceneId
	}
	return 0
}

func (m *RoleLoginAck) GetGwHostname() string {
	if m != nil {
		return m.GwHostname
	}
	return ""
}

func (m *RoleLoginAck) GetGwPort() int32 {
	if m != nil {
		return m.GwPort
	}
	return 0
}

func (m *RoleLoginAck) GetGsIndex() int32 {
	if m != nil {
		return m.GsIndex
	}
	return 0
}

func (m *RoleLoginAck) GetServerTime() int64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *RoleLoginAck) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

func (m *RoleLoginAck) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// 请求创建某个角色
type CreateRoleReq struct {
	RoleName             string   `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	LoginTime            uint32   `protobuf:"varint,2,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
	LoginStr             string   `protobuf:"bytes,3,opt,name=login_str,json=loginStr,proto3" json:"login_str,omitempty"`
	Server               uint32   `protobuf:"varint,4,opt,name=server,proto3" json:"server,omitempty"`
	AntiWallow           uint32   `protobuf:"varint,5,opt,name=anti_wallow,json=antiWallow,proto3" json:"anti_wallow,omitempty"`
	Avatar               uint32   `protobuf:"varint,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex                  uint32   `protobuf:"varint,7,opt,name=sex,proto3" json:"sex,omitempty"`
	PlatName             string   `protobuf:"bytes,8,opt,name=plat_name,json=platName,proto3" json:"plat_name,omitempty"`
	UserUuid             string   `protobuf:"bytes,9,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleReq) Reset()         { *m = CreateRoleReq{} }
func (m *CreateRoleReq) String() string { return proto.CompactTextString(m) }
func (*CreateRoleReq) ProtoMessage()    {}
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *CreateRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleReq.Unmarshal(m, b)
}
func (m *CreateRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleReq.Marshal(b, m, deterministic)
}
func (m *CreateRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleReq.Merge(m, src)
}
func (m *CreateRoleReq) XXX_Size() int {
	return xxx_messageInfo_CreateRoleReq.Size(m)
}
func (m *CreateRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleReq proto.InternalMessageInfo

func (m *CreateRoleReq) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *CreateRoleReq) GetLoginTime() uint32 {
	if m != nil {
		return m.LoginTime
	}
	return 0
}

func (m *CreateRoleReq) GetLoginStr() string {
	if m != nil {
		return m.LoginStr
	}
	return ""
}

func (m *CreateRoleReq) GetServer() uint32 {
	if m != nil {
		return m.Server
	}
	return 0
}

func (m *CreateRoleReq) GetAntiWallow() uint32 {
	if m != nil {
		return m.AntiWallow
	}
	return 0
}

func (m *CreateRoleReq) GetAvatar() uint32 {
	if m != nil {
		return m.Avatar
	}
	return 0
}

func (m *CreateRoleReq) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *CreateRoleReq) GetPlatName() string {
	if m != nil {
		return m.PlatName
	}
	return ""
}

func (m *CreateRoleReq) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

// 创建角色返回
type CreateRoleAck struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	RoleId               uint32   `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string   `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Avatar               uint32   `protobuf:"varint,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex                  uint32   `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	CreateTime           int32    `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoleAck) Reset()         { *m = CreateRoleAck{} }
func (m *CreateRoleAck) String() string { return proto.CompactTextString(m) }
func (*CreateRoleAck) ProtoMessage()    {}
func (*CreateRoleAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *CreateRoleAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoleAck.Unmarshal(m, b)
}
func (m *CreateRoleAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoleAck.Marshal(b, m, deterministic)
}
func (m *CreateRoleAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoleAck.Merge(m, src)
}
func (m *CreateRoleAck) XXX_Size() int {
	return xxx_messageInfo_CreateRoleAck.Size(m)
}
func (m *CreateRoleAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoleAck.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoleAck proto.InternalMessageInfo

func (m *CreateRoleAck) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CreateRoleAck) GetRoleId() uint32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *CreateRoleAck) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *CreateRoleAck) GetAvatar() uint32 {
	if m != nil {
		return m.Avatar
	}
	return 0
}

func (m *CreateRoleAck) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *CreateRoleAck) GetCreateTime() int32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

// 玩家进入场景
type UserEnterSceneReq struct {
	SceneId              int32    `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	SceneKey             int32    `protobuf:"varint,2,opt,name=scene_key,json=sceneKey,proto3" json:"scene_key,omitempty"`
	LastSceneId          int32    `protobuf:"varint,3,opt,name=last_scene_id,json=lastSceneId,proto3" json:"last_scene_id,omitempty"`
	RoleId               int32    `protobuf:"varint,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string   `protobuf:"bytes,5,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Time                 int32    `protobuf:"varint,6,opt,name=time,proto3" json:"time,omitempty"`
	IsLogin              uint32   `protobuf:"varint,7,opt,name=is_login,json=isLogin,proto3" json:"is_login,omitempty"`
	Reserved1            uint32   `protobuf:"varint,8,opt,name=reserved1,proto3" json:"reserved1,omitempty"`
	Server               int32    `protobuf:"varint,9,opt,name=server,proto3" json:"server,omitempty"`
	Key                  string   `protobuf:"bytes,10,opt,name=key,proto3" json:"key,omitempty"`
	UserUuid             string   `protobuf:"bytes,11,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Invitationstatus     int32    `protobuf:"varint,12,opt,name=invitationstatus,proto3" json:"invitationstatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEnterSceneReq) Reset()         { *m = UserEnterSceneReq{} }
func (m *UserEnterSceneReq) String() string { return proto.CompactTextString(m) }
func (*UserEnterSceneReq) ProtoMessage()    {}
func (*UserEnterSceneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *UserEnterSceneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEnterSceneReq.Unmarshal(m, b)
}
func (m *UserEnterSceneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEnterSceneReq.Marshal(b, m, deterministic)
}
func (m *UserEnterSceneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEnterSceneReq.Merge(m, src)
}
func (m *UserEnterSceneReq) XXX_Size() int {
	return xxx_messageInfo_UserEnterSceneReq.Size(m)
}
func (m *UserEnterSceneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEnterSceneReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserEnterSceneReq proto.InternalMessageInfo

func (m *UserEnterSceneReq) GetSceneId() int32 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *UserEnterSceneReq) GetSceneKey() int32 {
	if m != nil {
		return m.SceneKey
	}
	return 0
}

func (m *UserEnterSceneReq) GetLastSceneId() int32 {
	if m != nil {
		return m.LastSceneId
	}
	return 0
}

func (m *UserEnterSceneReq) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *UserEnterSceneReq) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *UserEnterSceneReq) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *UserEnterSceneReq) GetIsLogin() uint32 {
	if m != nil {
		return m.IsLogin
	}
	return 0
}

func (m *UserEnterSceneReq) GetReserved1() uint32 {
	if m != nil {
		return m.Reserved1
	}
	return 0
}

func (m *UserEnterSceneReq) GetServer() int32 {
	if m != nil {
		return m.Server
	}
	return 0
}

func (m *UserEnterSceneReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UserEnterSceneReq) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *UserEnterSceneReq) GetInvitationstatus() int32 {
	if m != nil {
		return m.Invitationstatus
	}
	return 0
}

// 玩家进入场景返回消息
type UserEnterSceneAck struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserEnterSceneAck) Reset()         { *m = UserEnterSceneAck{} }
func (m *UserEnterSceneAck) String() string { return proto.CompactTextString(m) }
func (*UserEnterSceneAck) ProtoMessage()    {}
func (*UserEnterSceneAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *UserEnterSceneAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserEnterSceneAck.Unmarshal(m, b)
}
func (m *UserEnterSceneAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserEnterSceneAck.Marshal(b, m, deterministic)
}
func (m *UserEnterSceneAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserEnterSceneAck.Merge(m, src)
}
func (m *UserEnterSceneAck) XXX_Size() int {
	return xxx_messageInfo_UserEnterSceneAck.Size(m)
}
func (m *UserEnterSceneAck) XXX_DiscardUnknown() {
	xxx_messageInfo_UserEnterSceneAck.DiscardUnknown(m)
}

var xxx_messageInfo_UserEnterSceneAck proto.InternalMessageInfo

func (m *UserEnterSceneAck) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

// 服务器推送角色列表
type RoleListNotify struct {
	ErrCode              int32       `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Count                int32       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	UserUuid             string      `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Wallet               string      `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Invitationstatus     int32       `protobuf:"varint,5,opt,name=invitationstatus,proto3" json:"invitationstatus,omitempty"`
	RoleItem             []*RoleItem `protobuf:"bytes,6,rep,name=roleItem,proto3" json:"roleItem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoleListNotify) Reset()         { *m = RoleListNotify{} }
func (m *RoleListNotify) String() string { return proto.CompactTextString(m) }
func (*RoleListNotify) ProtoMessage()    {}
func (*RoleListNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{6}
}

func (m *RoleListNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleListNotify.Unmarshal(m, b)
}
func (m *RoleListNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleListNotify.Marshal(b, m, deterministic)
}
func (m *RoleListNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleListNotify.Merge(m, src)
}
func (m *RoleListNotify) XXX_Size() int {
	return xxx_messageInfo_RoleListNotify.Size(m)
}
func (m *RoleListNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleListNotify.DiscardUnknown(m)
}

var xxx_messageInfo_RoleListNotify proto.InternalMessageInfo

func (m *RoleListNotify) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *RoleListNotify) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *RoleListNotify) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *RoleListNotify) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *RoleListNotify) GetInvitationstatus() int32 {
	if m != nil {
		return m.Invitationstatus
	}
	return 0
}

func (m *RoleListNotify) GetRoleItem() []*RoleItem {
	if m != nil {
		return m.RoleItem
	}
	return nil
}

// 进入场景广播消息
type EnterSceneNotify struct {
	Sceneid              int32    `protobuf:"varint,1,opt,name=sceneid,proto3" json:"sceneid,omitempty"`
	ObjId                int32    `protobuf:"varint,2,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
	OpenLine             int32    `protobuf:"varint,3,opt,name=open_line,json=openLine,proto3" json:"open_line,omitempty"`
	PosX                 float32  `protobuf:"fixed32,4,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY                 float32  `protobuf:"fixed32,5,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Hp                   int32    `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp                int32    `protobuf:"varint,7,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	SceneKey             int32    `protobuf:"varint,8,opt,name=scene_key,json=sceneKey,proto3" json:"scene_key,omitempty"`
	Height               float32  `protobuf:"fixed32,9,opt,name=height,proto3" json:"height,omitempty"`
	PosZ                 float32  `protobuf:"fixed32,10,opt,name=pos_z,json=posZ,proto3" json:"pos_z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterSceneNotify) Reset()         { *m = EnterSceneNotify{} }
func (m *EnterSceneNotify) String() string { return proto.CompactTextString(m) }
func (*EnterSceneNotify) ProtoMessage()    {}
func (*EnterSceneNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{7}
}

func (m *EnterSceneNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterSceneNotify.Unmarshal(m, b)
}
func (m *EnterSceneNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterSceneNotify.Marshal(b, m, deterministic)
}
func (m *EnterSceneNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterSceneNotify.Merge(m, src)
}
func (m *EnterSceneNotify) XXX_Size() int {
	return xxx_messageInfo_EnterSceneNotify.Size(m)
}
func (m *EnterSceneNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterSceneNotify.DiscardUnknown(m)
}

var xxx_messageInfo_EnterSceneNotify proto.InternalMessageInfo

func (m *EnterSceneNotify) GetSceneid() int32 {
	if m != nil {
		return m.Sceneid
	}
	return 0
}

func (m *EnterSceneNotify) GetObjId() int32 {
	if m != nil {
		return m.ObjId
	}
	return 0
}

func (m *EnterSceneNotify) GetOpenLine() int32 {
	if m != nil {
		return m.OpenLine
	}
	return 0
}

func (m *EnterSceneNotify) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *EnterSceneNotify) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *EnterSceneNotify) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *EnterSceneNotify) GetMaxHp() int32 {
	if m != nil {
		return m.MaxHp
	}
	return 0
}

func (m *EnterSceneNotify) GetSceneKey() int32 {
	if m != nil {
		return m.SceneKey
	}
	return 0
}

func (m *EnterSceneNotify) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *EnterSceneNotify) GetPosZ() float32 {
	if m != nil {
		return m.PosZ
	}
	return 0
}

// 玩家离开场景
type LeaveSceneNotify struct {
	Sceneid              int32    `protobuf:"varint,1,opt,name=sceneid,proto3" json:"sceneid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveSceneNotify) Reset()         { *m = LeaveSceneNotify{} }
func (m *LeaveSceneNotify) String() string { return proto.CompactTextString(m) }
func (*LeaveSceneNotify) ProtoMessage()    {}
func (*LeaveSceneNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{8}
}

func (m *LeaveSceneNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveSceneNotify.Unmarshal(m, b)
}
func (m *LeaveSceneNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveSceneNotify.Marshal(b, m, deterministic)
}
func (m *LeaveSceneNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveSceneNotify.Merge(m, src)
}
func (m *LeaveSceneNotify) XXX_Size() int {
	return xxx_messageInfo_LeaveSceneNotify.Size(m)
}
func (m *LeaveSceneNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveSceneNotify.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveSceneNotify proto.InternalMessageInfo

func (m *LeaveSceneNotify) GetSceneid() int32 {
	if m != nil {
		return m.Sceneid
	}
	return 0
}

// 广播移动消息
type ObjMoveNotify struct {
	Dir                  float32  `protobuf:"fixed32,1,opt,name=dir,proto3" json:"dir,omitempty"`
	SpeedX               float32  `protobuf:"fixed32,2,opt,name=speed_x,json=speedX,proto3" json:"speed_x,omitempty"`
	SpeedY               float32  `protobuf:"fixed32,3,opt,name=speed_y,json=speedY,proto3" json:"speed_y,omitempty"`
	SpeedZ               float32  `protobuf:"fixed32,4,opt,name=speed_z,json=speedZ,proto3" json:"speed_z,omitempty"`
	PosX                 float32  `protobuf:"fixed32,5,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY                 float32  `protobuf:"fixed32,6,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	PosZ                 float32  `protobuf:"fixed32,7,opt,name=pos_z,json=posZ,proto3" json:"pos_z,omitempty"`
	RotationX            float32  `protobuf:"fixed32,8,opt,name=rotation_x,json=rotationX,proto3" json:"rotation_x,omitempty"`
	RotationY            float32  `protobuf:"fixed32,9,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
	RotationZ            float32  `protobuf:"fixed32,10,opt,name=rotation_z,json=rotationZ,proto3" json:"rotation_z,omitempty"`
	Reserved             int32    `protobuf:"varint,11,opt,name=reserved,proto3" json:"reserved,omitempty"`
	ObjId                int32    `protobuf:"varint,12,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
	Distance             float32  `protobuf:"fixed32,13,opt,name=distance,proto3" json:"distance,omitempty"`
	MoveMode             uint32   `protobuf:"varint,14,opt,name=move_mode,json=moveMode,proto3" json:"move_mode,omitempty"`
	Reserve2             uint32   `protobuf:"varint,15,opt,name=reserve2,proto3" json:"reserve2,omitempty"`
	Height               float32  `protobuf:"fixed32,16,opt,name=height,proto3" json:"height,omitempty"`
	AccelerationX        float32  `protobuf:"fixed32,17,opt,name=acceleration_x,json=accelerationX,proto3" json:"acceleration_x,omitempty"`
	AccelerationY        float32  `protobuf:"fixed32,18,opt,name=acceleration_y,json=accelerationY,proto3" json:"acceleration_y,omitempty"`
	AccelerationZ        float32  `protobuf:"fixed32,19,opt,name=acceleration_z,json=accelerationZ,proto3" json:"acceleration_z,omitempty"`
	ControlRotationX     float32  `protobuf:"fixed32,20,opt,name=controlRotation_x,json=controlRotationX,proto3" json:"controlRotation_x,omitempty"`
	ControlRotationY     float32  `protobuf:"fixed32,21,opt,name=controlRotation_y,json=controlRotationY,proto3" json:"controlRotation_y,omitempty"`
	ControlRotationZ     float32  `protobuf:"fixed32,22,opt,name=controlRotation_z,json=controlRotationZ,proto3" json:"controlRotation_z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjMoveNotify) Reset()         { *m = ObjMoveNotify{} }
func (m *ObjMoveNotify) String() string { return proto.CompactTextString(m) }
func (*ObjMoveNotify) ProtoMessage()    {}
func (*ObjMoveNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{9}
}

func (m *ObjMoveNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjMoveNotify.Unmarshal(m, b)
}
func (m *ObjMoveNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjMoveNotify.Marshal(b, m, deterministic)
}
func (m *ObjMoveNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjMoveNotify.Merge(m, src)
}
func (m *ObjMoveNotify) XXX_Size() int {
	return xxx_messageInfo_ObjMoveNotify.Size(m)
}
func (m *ObjMoveNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjMoveNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ObjMoveNotify proto.InternalMessageInfo

func (m *ObjMoveNotify) GetDir() float32 {
	if m != nil {
		return m.Dir
	}
	return 0
}

func (m *ObjMoveNotify) GetSpeedX() float32 {
	if m != nil {
		return m.SpeedX
	}
	return 0
}

func (m *ObjMoveNotify) GetSpeedY() float32 {
	if m != nil {
		return m.SpeedY
	}
	return 0
}

func (m *ObjMoveNotify) GetSpeedZ() float32 {
	if m != nil {
		return m.SpeedZ
	}
	return 0
}

func (m *ObjMoveNotify) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *ObjMoveNotify) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *ObjMoveNotify) GetPosZ() float32 {
	if m != nil {
		return m.PosZ
	}
	return 0
}

func (m *ObjMoveNotify) GetRotationX() float32 {
	if m != nil {
		return m.RotationX
	}
	return 0
}

func (m *ObjMoveNotify) GetRotationY() float32 {
	if m != nil {
		return m.RotationY
	}
	return 0
}

func (m *ObjMoveNotify) GetRotationZ() float32 {
	if m != nil {
		return m.RotationZ
	}
	return 0
}

func (m *ObjMoveNotify) GetReserved() int32 {
	if m != nil {
		return m.Reserved
	}
	return 0
}

func (m *ObjMoveNotify) GetObjId() int32 {
	if m != nil {
		return m.ObjId
	}
	return 0
}

func (m *ObjMoveNotify) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *ObjMoveNotify) GetMoveMode() uint32 {
	if m != nil {
		return m.MoveMode
	}
	return 0
}

func (m *ObjMoveNotify) GetReserve2() uint32 {
	if m != nil {
		return m.Reserve2
	}
	return 0
}

func (m *ObjMoveNotify) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ObjMoveNotify) GetAccelerationX() float32 {
	if m != nil {
		return m.AccelerationX
	}
	return 0
}

func (m *ObjMoveNotify) GetAccelerationY() float32 {
	if m != nil {
		return m.AccelerationY
	}
	return 0
}

func (m *ObjMoveNotify) GetAccelerationZ() float32 {
	if m != nil {
		return m.AccelerationZ
	}
	return 0
}

func (m *ObjMoveNotify) GetControlRotationX() float32 {
	if m != nil {
		return m.ControlRotationX
	}
	return 0
}

func (m *ObjMoveNotify) GetControlRotationY() float32 {
	if m != nil {
		return m.ControlRotationY
	}
	return 0
}

func (m *ObjMoveNotify) GetControlRotationZ() float32 {
	if m != nil {
		return m.ControlRotationZ
	}
	return 0
}

// 玩家移动请求
type ObjMoveReq struct {
	Dir                  float32  `protobuf:"fixed32,1,opt,name=dir,proto3" json:"dir,omitempty"`
	SpeedX               float32  `protobuf:"fixed32,2,opt,name=speed_x,json=speedX,proto3" json:"speed_x,omitempty"`
	SpeedY               float32  `protobuf:"fixed32,3,opt,name=speed_y,json=speedY,proto3" json:"speed_y,omitempty"`
	SpeedZ               float32  `protobuf:"fixed32,4,opt,name=speed_z,json=speedZ,proto3" json:"speed_z,omitempty"`
	PosX                 float32  `protobuf:"fixed32,5,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY                 float32  `protobuf:"fixed32,6,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	PosZ                 float32  `protobuf:"fixed32,7,opt,name=pos_z,json=posZ,proto3" json:"pos_z,omitempty"`
	RotationX            float32  `protobuf:"fixed32,8,opt,name=rotation_x,json=rotationX,proto3" json:"rotation_x,omitempty"`
	RotationY            float32  `protobuf:"fixed32,9,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
	RotationZ            float32  `protobuf:"fixed32,10,opt,name=rotation_z,json=rotationZ,proto3" json:"rotation_z,omitempty"`
	Distance             float32  `protobuf:"fixed32,11,opt,name=distance,proto3" json:"distance,omitempty"`
	Height               float32  `protobuf:"fixed32,12,opt,name=height,proto3" json:"height,omitempty"`
	AccelerationX        float32  `protobuf:"fixed32,13,opt,name=acceleration_x,json=accelerationX,proto3" json:"acceleration_x,omitempty"`
	AccelerationY        float32  `protobuf:"fixed32,14,opt,name=acceleration_y,json=accelerationY,proto3" json:"acceleration_y,omitempty"`
	AccelerationZ        float32  `protobuf:"fixed32,15,opt,name=acceleration_z,json=accelerationZ,proto3" json:"acceleration_z,omitempty"`
	ControlRotationX     float32  `protobuf:"fixed32,16,opt,name=controlRotation_x,json=controlRotationX,proto3" json:"controlRotation_x,omitempty"`
	ControlRotationY     float32  `protobuf:"fixed32,17,opt,name=controlRotation_y,json=controlRotationY,proto3" json:"controlRotation_y,omitempty"`
	ControlRotationZ     float32  `protobuf:"fixed32,18,opt,name=controlRotation_z,json=controlRotationZ,proto3" json:"controlRotation_z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjMoveReq) Reset()         { *m = ObjMoveReq{} }
func (m *ObjMoveReq) String() string { return proto.CompactTextString(m) }
func (*ObjMoveReq) ProtoMessage()    {}
func (*ObjMoveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{10}
}

func (m *ObjMoveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjMoveReq.Unmarshal(m, b)
}
func (m *ObjMoveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjMoveReq.Marshal(b, m, deterministic)
}
func (m *ObjMoveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjMoveReq.Merge(m, src)
}
func (m *ObjMoveReq) XXX_Size() int {
	return xxx_messageInfo_ObjMoveReq.Size(m)
}
func (m *ObjMoveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjMoveReq.DiscardUnknown(m)
}

var xxx_messageInfo_ObjMoveReq proto.InternalMessageInfo

func (m *ObjMoveReq) GetDir() float32 {
	if m != nil {
		return m.Dir
	}
	return 0
}

func (m *ObjMoveReq) GetSpeedX() float32 {
	if m != nil {
		return m.SpeedX
	}
	return 0
}

func (m *ObjMoveReq) GetSpeedY() float32 {
	if m != nil {
		return m.SpeedY
	}
	return 0
}

func (m *ObjMoveReq) GetSpeedZ() float32 {
	if m != nil {
		return m.SpeedZ
	}
	return 0
}

func (m *ObjMoveReq) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *ObjMoveReq) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *ObjMoveReq) GetPosZ() float32 {
	if m != nil {
		return m.PosZ
	}
	return 0
}

func (m *ObjMoveReq) GetRotationX() float32 {
	if m != nil {
		return m.RotationX
	}
	return 0
}

func (m *ObjMoveReq) GetRotationY() float32 {
	if m != nil {
		return m.RotationY
	}
	return 0
}

func (m *ObjMoveReq) GetRotationZ() float32 {
	if m != nil {
		return m.RotationZ
	}
	return 0
}

func (m *ObjMoveReq) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *ObjMoveReq) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ObjMoveReq) GetAccelerationX() float32 {
	if m != nil {
		return m.AccelerationX
	}
	return 0
}

func (m *ObjMoveReq) GetAccelerationY() float32 {
	if m != nil {
		return m.AccelerationY
	}
	return 0
}

func (m *ObjMoveReq) GetAccelerationZ() float32 {
	if m != nil {
		return m.AccelerationZ
	}
	return 0
}

func (m *ObjMoveReq) GetControlRotationX() float32 {
	if m != nil {
		return m.ControlRotationX
	}
	return 0
}

func (m *ObjMoveReq) GetControlRotationY() float32 {
	if m != nil {
		return m.ControlRotationY
	}
	return 0
}

func (m *ObjMoveReq) GetControlRotationZ() float32 {
	if m != nil {
		return m.ControlRotationZ
	}
	return 0
}

// 进入视野广播
type VisibleObjEnterRoleNotify struct {
	Dir                  float32  `protobuf:"fixed32,1,opt,name=dir,proto3" json:"dir,omitempty"`
	MoveModeParam        uint32   `protobuf:"varint,2,opt,name=move_mode_param,json=moveModeParam,proto3" json:"move_mode_param,omitempty"`
	RoleStatus           uint32   `protobuf:"varint,3,opt,name=role_status,json=roleStatus,proto3" json:"role_status,omitempty"`
	ObjId                uint32   `protobuf:"varint,4,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
	RoleId               int32    `protobuf:"varint,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string   `protobuf:"bytes,6,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Hp                   int32    `protobuf:"varint,7,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp                int32    `protobuf:"varint,8,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Level                uint32   `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	Sex                  uint32   `protobuf:"varint,10,opt,name=sex,proto3" json:"sex,omitempty"`
	Speed                uint32   `protobuf:"varint,11,opt,name=speed,proto3" json:"speed,omitempty"`
	PosX                 float32  `protobuf:"fixed32,12,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY                 float32  `protobuf:"fixed32,13,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Distance             float32  `protobuf:"fixed32,14,opt,name=distance,proto3" json:"distance,omitempty"`
	NameColor            uint32   `protobuf:"varint,15,opt,name=name_color,json=nameColor,proto3" json:"name_color,omitempty"`
	MoveMode             uint32   `protobuf:"varint,16,opt,name=move_mode,json=moveMode,proto3" json:"move_mode,omitempty"`
	Avatar               uint32   `protobuf:"varint,17,opt,name=avatar,proto3" json:"avatar,omitempty"`
	PosZ                 float32  `protobuf:"fixed32,18,opt,name=pos_z,json=posZ,proto3" json:"pos_z,omitempty"`
	RotationX            float32  `protobuf:"fixed32,19,opt,name=rotation_x,json=rotationX,proto3" json:"rotation_x,omitempty"`
	RotationY            float32  `protobuf:"fixed32,20,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
	RotationZ            float32  `protobuf:"fixed32,21,opt,name=rotation_z,json=rotationZ,proto3" json:"rotation_z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisibleObjEnterRoleNotify) Reset()         { *m = VisibleObjEnterRoleNotify{} }
func (m *VisibleObjEnterRoleNotify) String() string { return proto.CompactTextString(m) }
func (*VisibleObjEnterRoleNotify) ProtoMessage()    {}
func (*VisibleObjEnterRoleNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{11}
}

func (m *VisibleObjEnterRoleNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisibleObjEnterRoleNotify.Unmarshal(m, b)
}
func (m *VisibleObjEnterRoleNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisibleObjEnterRoleNotify.Marshal(b, m, deterministic)
}
func (m *VisibleObjEnterRoleNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisibleObjEnterRoleNotify.Merge(m, src)
}
func (m *VisibleObjEnterRoleNotify) XXX_Size() int {
	return xxx_messageInfo_VisibleObjEnterRoleNotify.Size(m)
}
func (m *VisibleObjEnterRoleNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_VisibleObjEnterRoleNotify.DiscardUnknown(m)
}

var xxx_messageInfo_VisibleObjEnterRoleNotify proto.InternalMessageInfo

func (m *VisibleObjEnterRoleNotify) GetDir() float32 {
	if m != nil {
		return m.Dir
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetMoveModeParam() uint32 {
	if m != nil {
		return m.MoveModeParam
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetRoleStatus() uint32 {
	if m != nil {
		return m.RoleStatus
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetObjId() uint32 {
	if m != nil {
		return m.ObjId
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *VisibleObjEnterRoleNotify) GetHp() int32 {
	if m != nil {
		return m.Hp
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetMaxHp() int32 {
	if m != nil {
		return m.MaxHp
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetNameColor() uint32 {
	if m != nil {
		return m.NameColor
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetMoveMode() uint32 {
	if m != nil {
		return m.MoveMode
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetAvatar() uint32 {
	if m != nil {
		return m.Avatar
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetPosZ() float32 {
	if m != nil {
		return m.PosZ
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetRotationX() float32 {
	if m != nil {
		return m.RotationX
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetRotationY() float32 {
	if m != nil {
		return m.RotationY
	}
	return 0
}

func (m *VisibleObjEnterRoleNotify) GetRotationZ() float32 {
	if m != nil {
		return m.RotationZ
	}
	return 0
}

// 角色信息
type RoleItem struct {
	RoleId               int32    `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName             string   `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Avatar               int32    `protobuf:"varint,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Sex                  int32    `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	CreateTime           uint32   `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	LastLoginTime        uint32   `protobuf:"varint,6,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleItem) Reset()         { *m = RoleItem{} }
func (m *RoleItem) String() string { return proto.CompactTextString(m) }
func (*RoleItem) ProtoMessage()    {}
func (*RoleItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{12}
}

func (m *RoleItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleItem.Unmarshal(m, b)
}
func (m *RoleItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleItem.Marshal(b, m, deterministic)
}
func (m *RoleItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleItem.Merge(m, src)
}
func (m *RoleItem) XXX_Size() int {
	return xxx_messageInfo_RoleItem.Size(m)
}
func (m *RoleItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleItem.DiscardUnknown(m)
}

var xxx_messageInfo_RoleItem proto.InternalMessageInfo

func (m *RoleItem) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleItem) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

func (m *RoleItem) GetAvatar() int32 {
	if m != nil {
		return m.Avatar
	}
	return 0
}

func (m *RoleItem) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *RoleItem) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *RoleItem) GetLastLoginTime() uint32 {
	if m != nil {
		return m.LastLoginTime
	}
	return 0
}

// 登录游戏
type LoginMsgReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Wallet               string   `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Invitationstatus     int32    `protobuf:"varint,5,opt,name=invitationstatus,proto3" json:"invitationstatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginMsgReq) Reset()         { *m = LoginMsgReq{} }
func (m *LoginMsgReq) String() string { return proto.CompactTextString(m) }
func (*LoginMsgReq) ProtoMessage()    {}
func (*LoginMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{13}
}

func (m *LoginMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginMsgReq.Unmarshal(m, b)
}
func (m *LoginMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginMsgReq.Marshal(b, m, deterministic)
}
func (m *LoginMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginMsgReq.Merge(m, src)
}
func (m *LoginMsgReq) XXX_Size() int {
	return xxx_messageInfo_LoginMsgReq.Size(m)
}
func (m *LoginMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginMsgReq proto.InternalMessageInfo

func (m *LoginMsgReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginMsgReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginMsgReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *LoginMsgReq) GetWallet() string {
	if m != nil {
		return m.Wallet
	}
	return ""
}

func (m *LoginMsgReq) GetInvitationstatus() int32 {
	if m != nil {
		return m.Invitationstatus
	}
	return 0
}

func init() {
	proto.RegisterEnum("CreateRoleAck_RET_TYPE", CreateRoleAck_RET_TYPE_name, CreateRoleAck_RET_TYPE_value)
	proto.RegisterEnum("RoleListNotify_LoginAckCode", RoleListNotify_LoginAckCode_name, RoleListNotify_LoginAckCode_value)
	proto.RegisterType((*RoleLoginReq)(nil), "RoleLoginReq")
	proto.RegisterType((*RoleLoginAck)(nil), "RoleLoginAck")
	proto.RegisterType((*CreateRoleReq)(nil), "CreateRoleReq")
	proto.RegisterType((*CreateRoleAck)(nil), "CreateRoleAck")
	proto.RegisterType((*UserEnterSceneReq)(nil), "UserEnterSceneReq")
	proto.RegisterType((*UserEnterSceneAck)(nil), "UserEnterSceneAck")
	proto.RegisterType((*RoleListNotify)(nil), "RoleListNotify")
	proto.RegisterType((*EnterSceneNotify)(nil), "EnterSceneNotify")
	proto.RegisterType((*LeaveSceneNotify)(nil), "LeaveSceneNotify")
	proto.RegisterType((*ObjMoveNotify)(nil), "ObjMoveNotify")
	proto.RegisterType((*ObjMoveReq)(nil), "ObjMoveReq")
	proto.RegisterType((*VisibleObjEnterRoleNotify)(nil), "VisibleObjEnterRoleNotify")
	proto.RegisterType((*RoleItem)(nil), "RoleItem")
	proto.RegisterType((*LoginMsgReq)(nil), "LoginMsgReq")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 1539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0xad, 0x1e, 0x94, 0xa9, 0x2b, 0xd3, 0xa6, 0x27, 0xb2, 0xc3, 0xd8, 0x09, 0x62, 0x10, 0x48,
	0x61, 0xf4, 0x11, 0xa0, 0xe9, 0x17, 0x28, 0x0e, 0x9b, 0x08, 0x95, 0x25, 0x63, 0x24, 0xc7, 0x96,
	0x51, 0x60, 0x40, 0x4b, 0x53, 0x99, 0x0e, 0x45, 0xaa, 0x24, 0x65, 0x5b, 0xde, 0x77, 0xd3, 0x4d,
	0x81, 0x7e, 0x43, 0xff, 0xa0, 0xed, 0xba, 0xfb, 0xa2, 0xe8, 0x3b, 0x9f, 0xd0, 0xaf, 0xe8, 0xa6,
	0x98, 0x07, 0x45, 0x8a, 0x96, 0x5c, 0x07, 0xc8, 0xae, 0x1b, 0x81, 0xf7, 0x31, 0x33, 0x77, 0xee,
	0x3d, 0x67, 0xe6, 0x8e, 0xa0, 0xe2, 0xfa, 0x03, 0xc7, 0x7b, 0x3c, 0x0a, 0xfc, 0xc8, 0x37, 0x3f,
	0x83, 0x65, 0xec, 0xbb, 0xb4, 0xc1, 0x54, 0x98, 0x7e, 0x81, 0x36, 0xa0, 0x64, 0xf7, 0x7a, 0xfe,
	0x38, 0x32, 0x72, 0xdb, 0xb9, 0x9d, 0x32, 0x96, 0x12, 0xba, 0x0b, 0x4b, 0x81, 0xef, 0x52, 0xe2,
	0xf4, 0x8d, 0xfc, 0x76, 0x6e, 0x47, 0xc1, 0x25, 0x26, 0xd6, 0xfb, 0x68, 0x0b, 0xca, 0xdc, 0xe0,
	0xd9, 0x43, 0x6a, 0x14, 0xf8, 0x18, 0x95, 0x29, 0x9a, 0xf6, 0x90, 0x9a, 0x3f, 0xe5, 0x53, 0xd3,
	0xd7, 0x7a, 0xaf, 0xde, 0xee, 0xf4, 0xe8, 0x1e, 0xa8, 0x61, 0x8f, 0x7a, 0x7c, 0x58, 0x91, 0x0f,
	0x5b, 0xe2, 0x72, 0xbd, 0x8f, 0x4c, 0xd0, 0x5c, 0x3b, 0x8c, 0xc8, 0xd4, 0xae, 0x70, 0x7b, 0x85,
	0x29, 0xdb, 0xd2, 0xe7, 0x21, 0x54, 0x06, 0x17, 0xe4, 0xd4, 0x0f, 0x23, 0x3e, 0x7b, 0x89, 0xcf,
	0x0e, 0x83, 0x8b, 0x17, 0x52, 0xc3, 0xa2, 0x1a, 0x5c, 0x90, 0x91, 0x1f, 0x44, 0xc6, 0x92, 0x88,
	0x6a, 0x70, 0xb1, 0xef, 0x07, 0x11, 0x5b, 0x78, 0x10, 0x12, 0xc7, 0xeb, 0xd3, 0x4b, 0x43, 0x15,
	0x0b, 0x0f, 0xc2, 0x3a, 0x13, 0xd9, 0xa4, 0x21, 0x0d, 0xce, 0x69, 0x40, 0x22, 0x67, 0x48, 0x8d,
	0xf2, 0x76, 0x6e, 0xa7, 0x80, 0x41, 0xa8, 0x3a, 0xce, 0x90, 0x0a, 0x87, 0x30, 0x74, 0x7c, 0x8f,
	0xbc, 0xa2, 0x13, 0x03, 0xc4, 0xaa, 0x52, 0xf5, 0x29, 0x9d, 0xb0, 0x1c, 0x05, 0x34, 0x1c, 0xbb,
	0x91, 0x51, 0x91, 0xa9, 0xe0, 0x92, 0xf9, 0x65, 0x1e, 0xb4, 0xdd, 0x80, 0xda, 0x11, 0x65, 0x29,
	0x65, 0xc5, 0x9a, 0x49, 0x4e, 0x2e, 0x93, 0x9c, 0x07, 0x00, 0xbc, 0xd0, 0x22, 0x0e, 0x96, 0x55,
	0x0d, 0x97, 0xb9, 0x86, 0x87, 0xb1, 0x05, 0x42, 0x20, 0x61, 0x14, 0xc4, 0x89, 0xe5, 0x8a, 0x76,
	0x14, 0xb0, 0x10, 0x44, 0xc4, 0x3c, 0xad, 0x1a, 0x96, 0x12, 0x8b, 0xdd, 0xf6, 0x22, 0x87, 0x5c,
	0xd8, 0xae, 0xeb, 0x5f, 0xf0, 0x9c, 0x6a, 0x18, 0x98, 0xea, 0x90, 0x6b, 0x78, 0x7d, 0xcf, 0xed,
	0xc8, 0x0e, 0x78, 0x36, 0x35, 0x2c, 0x25, 0xa4, 0x43, 0x21, 0xa4, 0x97, 0x3c, 0x8b, 0x1a, 0x66,
	0x9f, 0x6c, 0xfd, 0x91, 0x6b, 0x47, 0x22, 0x76, 0x55, 0xac, 0xcf, 0x14, 0x3c, 0xf6, 0x2d, 0x28,
	0x8f, 0x43, 0x1a, 0x90, 0xf1, 0xd8, 0xe9, 0xf3, 0x14, 0x96, 0xb1, 0xca, 0x14, 0x07, 0x63, 0xa7,
	0x6f, 0xfe, 0x38, 0x93, 0x07, 0x86, 0x2a, 0x03, 0x96, 0x68, 0x10, 0xec, 0xfa, 0x7d, 0x91, 0x05,
	0x05, 0xc7, 0x62, 0x16, 0x57, 0xda, 0xed, 0x70, 0x95, 0xec, 0xa2, 0x38, 0x6f, 0x17, 0x4a, 0xb2,
	0x8b, 0x87, 0x50, 0xe9, 0xf1, 0x50, 0x44, 0x96, 0x4b, 0x7c, 0x75, 0x10, 0x2a, 0x96, 0x66, 0xf3,
	0x9b, 0x1c, 0xa8, 0xd8, 0xea, 0x90, 0x4e, 0x77, 0xdf, 0x42, 0x55, 0xd0, 0xb1, 0xd5, 0x3e, 0x68,
	0x08, 0x91, 0xb4, 0x0f, 0x76, 0x77, 0xf5, 0x77, 0x90, 0x01, 0xd5, 0xb4, 0xb6, 0xd9, 0x22, 0xed,
	0xfd, 0xda, 0xae, 0xa5, 0xe7, 0xd0, 0x26, 0x6c, 0xa4, 0x2d, 0xd6, 0x51, 0xbd, 0xdd, 0x21, 0xcd,
	0xda, 0x9e, 0xa5, 0xe7, 0xd1, 0x7d, 0x30, 0x66, 0x46, 0xd5, 0xf6, 0x2c, 0x52, 0x6f, 0xbe, 0xac,
	0x35, 0xea, 0xcf, 0xf4, 0x42, 0xd6, 0xda, 0xb6, 0xf0, 0x4b, 0x0b, 0x93, 0x46, 0x7d, 0xaf, 0xde,
	0xd1, 0x8b, 0xe6, 0xdf, 0x79, 0x58, 0x3b, 0x08, 0x69, 0x60, 0x79, 0x11, 0x0d, 0x38, 0x1b, 0x18,
	0x9a, 0xd2, 0x6c, 0xca, 0xcd, 0xb2, 0x69, 0x0b, 0xca, 0xc2, 0xc4, 0x10, 0x2b, 0x08, 0x2a, 0x7c,
	0x19, 0x5e, 0xaf, 0x51, 0xad, 0x70, 0x9d, 0x6a, 0xa9, 0x3a, 0x14, 0x17, 0xf3, 0x5b, 0xc9, 0xd4,
	0x01, 0x41, 0x31, 0x95, 0x56, 0xfe, 0xcd, 0xa2, 0x74, 0x42, 0xc2, 0x91, 0x2a, 0xe1, 0xb4, 0xe4,
	0x84, 0xfc, 0x7c, 0x41, 0xf7, 0xa1, 0x1c, 0x50, 0x8e, 0xd4, 0xfe, 0x47, 0x1c, 0x52, 0x1a, 0x4e,
	0x14, 0x29, 0x4c, 0x97, 0x45, 0x04, 0x12, 0xd3, 0x3a, 0x14, 0x12, 0x1e, 0xb2, 0xcf, 0x59, 0xf4,
	0x55, 0x66, 0xd1, 0x87, 0xde, 0x03, 0xdd, 0xf1, 0xce, 0x9d, 0xc8, 0x8e, 0x1c, 0xdf, 0x0b, 0x23,
	0x3b, 0x1a, 0x87, 0xc6, 0x32, 0x9f, 0xf0, 0x9a, 0xde, 0xfc, 0x30, 0x9b, 0xe6, 0x1b, 0xc1, 0x6a,
	0xbe, 0x2e, 0xc0, 0x0a, 0x3f, 0x2d, 0x9d, 0x30, 0x6a, 0xfa, 0x91, 0xf3, 0xf9, 0xe4, 0x06, 0x64,
	0x57, 0x41, 0xe9, 0xf9, 0x63, 0x2f, 0x92, 0xe5, 0x10, 0xc2, 0x6c, 0xe8, 0x85, 0x4c, 0xe8, 0x1b,
	0x50, 0x62, 0xc4, 0xa5, 0x11, 0xaf, 0x41, 0x19, 0x4b, 0x69, 0xee, 0x96, 0x94, 0xf9, 0x5b, 0x42,
	0x8f, 0x80, 0x97, 0xa7, 0x1e, 0xd1, 0xa1, 0x51, 0xda, 0x2e, 0xec, 0x54, 0x9e, 0x94, 0x1f, 0x63,
	0xa9, 0xc0, 0x53, 0x93, 0xf9, 0x55, 0x1e, 0x96, 0xe3, 0x43, 0x5f, 0x86, 0xab, 0x37, 0x5a, 0xcf,
	0xeb, 0x4d, 0x22, 0x61, 0xd9, 0x3e, 0x60, 0xd0, 0xaf, 0xc2, 0xaa, 0xd0, 0x36, 0x5b, 0xa4, 0xf3,
	0x02, 0x5b, 0xb5, 0x67, 0xfa, 0xcf, 0x2a, 0xba, 0x0b, 0x48, 0x68, 0x25, 0x6c, 0x2d, 0x8c, 0x5b,
	0x58, 0xff, 0x25, 0x65, 0x90, 0x93, 0x70, 0x42, 0xe8, 0xbf, 0xaa, 0x68, 0x13, 0xd6, 0xe5, 0x88,
	0x5d, 0xab, 0xc9, 0x28, 0x14, 0xdb, 0x7e, 0x53, 0xd1, 0x7d, 0xb8, 0x3b, 0x33, 0xa8, 0xd9, 0x22,
	0xcf, 0x6b, 0x1d, 0xeb, 0xb0, 0xd6, 0xd5, 0x7f, 0x57, 0xd1, 0x3d, 0xa8, 0x66, 0xad, 0xb8, 0xd5,
	0xb0, 0xf4, 0x3f, 0x54, 0xb4, 0x01, 0x6b, 0xc2, 0x24, 0x22, 0x23, 0x4f, 0x0f, 0xda, 0x5d, 0xfd,
	0xcf, 0x54, 0x14, 0xe2, 0xf7, 0x93, 0x16, 0x7e, 0x5a, 0x7f, 0xa6, 0xff, 0x95, 0x1a, 0x50, 0x6b,
	0x76, 0xea, 0xe4, 0xb0, 0xd6, 0x68, 0xb4, 0x0e, 0xf5, 0xd7, 0xaa, 0xf9, 0x4f, 0x0e, 0xf4, 0x04,
	0x03, 0x49, 0x65, 0x39, 0x61, 0x32, 0x64, 0x73, 0xfa, 0x68, 0x1d, 0x4a, 0xfe, 0xc9, 0x59, 0x72,
	0x15, 0x2a, 0xfe, 0xc9, 0x99, 0x60, 0x8a, 0x3f, 0xa2, 0x1e, 0x71, 0x1d, 0x8f, 0x4a, 0x8a, 0xa9,
	0x4c, 0xd1, 0x70, 0x3c, 0x8a, 0xee, 0x80, 0x32, 0xf2, 0x43, 0x72, 0xc9, 0x2b, 0x9b, 0xc7, 0xc5,
	0x91, 0x1f, 0x1e, 0xc5, 0xca, 0x09, 0x2f, 0xa6, 0x50, 0x76, 0xd1, 0x0a, 0xe4, 0x4f, 0x47, 0x92,
	0x51, 0xf9, 0xd3, 0x11, 0x5b, 0x6d, 0x68, 0x5f, 0x92, 0xd3, 0x91, 0xbc, 0xe2, 0x94, 0xa1, 0x7d,
	0xf9, 0x62, 0x34, 0xcb, 0x78, 0x35, 0xc3, 0xf8, 0x0d, 0x28, 0x9d, 0x52, 0x67, 0x70, 0x1a, 0x71,
	0x2a, 0xe5, 0xb1, 0x94, 0xe2, 0x05, 0xaf, 0x38, 0x99, 0xc4, 0x82, 0xc7, 0xe6, 0x07, 0xa0, 0x37,
	0xa8, 0x7d, 0x4e, 0x6f, 0xb5, 0x79, 0xf3, 0x5b, 0x05, 0xb4, 0xd6, 0xc9, 0xd9, 0x9e, 0x7f, 0x1e,
	0xfb, 0xea, 0x50, 0xe8, 0x3b, 0x01, 0xf7, 0xcb, 0x63, 0xf6, 0xc9, 0x0e, 0x93, 0x70, 0x44, 0x69,
	0x9f, 0x5c, 0xf2, 0x0c, 0xe5, 0x71, 0x89, 0x8b, 0x47, 0x89, 0x61, 0xc2, 0x13, 0x14, 0x1b, 0xba,
	0x89, 0xe1, 0x4a, 0x26, 0x48, 0x18, 0x8e, 0x93, 0xbc, 0x29, 0xf3, 0xf2, 0x56, 0x4a, 0xe5, 0x6d,
	0xba, 0xb7, 0xa5, 0x64, 0x6f, 0xec, 0x8e, 0x0d, 0x7c, 0xc1, 0x0f, 0x22, 0x3a, 0x81, 0x3c, 0x2e,
	0xc7, 0x9a, 0xa3, 0x19, 0xf3, 0x44, 0xe6, 0x6a, 0x6a, 0xee, 0xce, 0x98, 0xe3, 0x9c, 0x4d, 0xcd,
	0xc7, 0x68, 0x13, 0xd4, 0xf8, 0xf4, 0x92, 0x9d, 0xc0, 0x54, 0x4e, 0x61, 0x64, 0x39, 0x8d, 0x91,
	0x4d, 0x50, 0xfb, 0x4e, 0x18, 0xd9, 0x5e, 0x8f, 0x1a, 0x1a, 0x9f, 0x6f, 0x2a, 0xb3, 0x8a, 0x0e,
	0xfd, 0x73, 0x4a, 0x86, 0xec, 0x30, 0x59, 0xe1, 0xa7, 0xa3, 0xca, 0x14, 0x7b, 0x8c, 0x9e, 0xc9,
	0x5a, 0x4f, 0x8c, 0x55, 0x61, 0x8b, 0xe5, 0x54, 0xb5, 0xf5, 0x99, 0x6a, 0x3f, 0x82, 0x15, 0xbb,
	0xd7, 0xa3, 0x2e, 0x0d, 0xe2, 0x04, 0xac, 0x71, 0xbb, 0x96, 0xd6, 0x1e, 0x5d, 0x73, 0x9b, 0x18,
	0xe8, 0xba, 0x5b, 0xf7, 0x9a, 0xdb, 0x95, 0x71, 0xe7, 0xba, 0xdb, 0x31, 0x7a, 0x1f, 0xd6, 0x7a,
	0xbe, 0x17, 0x05, 0xbe, 0x8b, 0x93, 0xc4, 0x57, 0xb9, 0xa7, 0x9e, 0x31, 0x1c, 0xcd, 0x73, 0x9e,
	0x18, 0xeb, 0x73, 0x9d, 0xbb, 0xf3, 0x9c, 0xaf, 0x8c, 0x8d, 0xb9, 0xce, 0xc7, 0xe6, 0x0f, 0x45,
	0x00, 0x09, 0x53, 0x76, 0x75, 0xfe, 0x9f, 0x31, 0x3a, 0x05, 0x5c, 0x25, 0x03, 0xb8, 0x04, 0x37,
	0xcb, 0xff, 0x81, 0x1b, 0xed, 0x76, 0xb8, 0x59, 0xb9, 0x1d, 0x6e, 0x56, 0x6f, 0x8d, 0x1b, 0xfd,
	0x4d, 0x70, 0xb3, 0xf6, 0x26, 0xb8, 0x41, 0x0b, 0x70, 0xf3, 0x7d, 0x11, 0xee, 0xbd, 0x74, 0x42,
	0xe7, 0xc4, 0xa5, 0xad, 0x93, 0x33, 0x7e, 0x29, 0xb0, 0xdb, 0x73, 0xe1, 0x51, 0xf7, 0x2e, 0xac,
	0x4e, 0x49, 0x4b, 0x46, 0x76, 0x60, 0x0f, 0x65, 0x1f, 0xab, 0xc5, 0xd4, 0xdd, 0x67, 0x4a, 0xd6,
	0x87, 0xf2, 0x36, 0x4a, 0xde, 0xde, 0x05, 0xd1, 0x98, 0x33, 0x55, 0x5b, 0xdc, 0xdb, 0xc9, 0x81,
	0x21, 0x5a, 0x5a, 0x79, 0x60, 0xa4, 0xfa, 0x32, 0x65, 0x71, 0x5f, 0x56, 0xca, 0xf4, 0x65, 0xe2,
	0x0e, 0x59, 0x9a, 0x73, 0x87, 0xa8, 0xe9, 0x3b, 0xa4, 0x0a, 0x8a, 0x4b, 0xcf, 0xa9, 0xcb, 0x51,
	0xa5, 0x61, 0x21, 0xc4, 0x4d, 0x34, 0x24, 0x4d, 0x74, 0x15, 0x14, 0x0e, 0x75, 0x8e, 0x20, 0x0d,
	0x0b, 0x21, 0x81, 0xfd, 0xf2, 0x3c, 0xd8, 0x6b, 0x29, 0xd8, 0xa7, 0x41, 0xb8, 0x92, 0x01, 0xe1,
	0x03, 0x00, 0xb6, 0x05, 0xd2, 0xf3, 0x5d, 0x3f, 0x90, 0x47, 0x5b, 0x99, 0x69, 0x76, 0x99, 0x62,
	0xf6, 0x50, 0xd4, 0x33, 0x87, 0x62, 0xf2, 0x0c, 0x58, 0x9b, 0x79, 0x06, 0x4c, 0x69, 0x86, 0x16,
	0xd2, 0xec, 0xce, 0xcd, 0x34, 0xab, 0xde, 0x4c, 0xb3, 0xf5, 0x0c, 0xcd, 0xcc, 0xef, 0xd8, 0x2b,
	0x42, 0xf6, 0x56, 0xe9, 0x9a, 0xe5, 0x16, 0xd7, 0x2c, 0xbf, 0xf0, 0x4d, 0x23, 0x7a, 0x87, 0xcc,
	0x9b, 0x46, 0x74, 0xe5, 0xf3, 0xde, 0x34, 0xf2, 0x91, 0x97, 0xbc, 0x69, 0x18, 0x28, 0x79, 0xc3,
	0x9f, 0x7a, 0x5e, 0x8a, 0xd7, 0x1e, 0x7f, 0x07, 0x34, 0xe2, 0x27, 0xa6, 0xf9, 0x75, 0x0e, 0x2a,
	0x5c, 0xda, 0x0b, 0x07, 0xec, 0x94, 0x44, 0x50, 0x4c, 0xbd, 0x54, 0xf9, 0x37, 0xab, 0x7d, 0xe4,
	0xbf, 0xa2, 0x9e, 0x8c, 0x57, 0x08, 0xcc, 0x33, 0xd5, 0xc1, 0xf2, 0xef, 0xb7, 0xd1, 0xbd, 0x9e,
	0x94, 0xf8, 0x9f, 0x1e, 0x1f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xba, 0x0c, 0x84, 0x6b, 0x03,
	0x11, 0x00, 0x00,
}
