// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scene.proto

package scene

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SceneMsgId int32

const (
	SceneMsgId_MSG_ID                           SceneMsgId = 0
	SceneMsgId_SCENE_ROLEJUMPREQ_REQ            SceneMsgId = 3101
	SceneMsgId_SCENE_ROLEJUMPACK_ACK            SceneMsgId = 3102
	SceneMsgId_SCENE_ROLEREALIVENOTIFY_NOTIFY   SceneMsgId = 1302
	SceneMsgId_SCENE_CHANNELCHATREQ_REQ         SceneMsgId = 8150
	SceneMsgId_SCENE_CHANNELCHATACK_ACK         SceneMsgId = 8100
	SceneMsgId_SCENE_ACTIVITYREADYNOTIFY_NOTIFY SceneMsgId = 8161
	SceneMsgId_SCENE_ACTIVITYSTARTNOTIFY_NOTIFY SceneMsgId = 8162
	SceneMsgId_SCENE_JOINACTIVITYREQ_REQ        SceneMsgId = 8163
	SceneMsgId_SCENE_JOINACTIVITYACK_ACK        SceneMsgId = 8164
	SceneMsgId_SCENE_MAZEGETGEMREQ_REQ          SceneMsgId = 8200
	SceneMsgId_SCENE_AREAINITNOTIFY_NOTIFY      SceneMsgId = 9100
	SceneMsgId_SCENE_AREATRADENOTIFY_NOTIFY     SceneMsgId = 9101
	SceneMsgId_SCENE_SERVERTIMEREQ_REQ          SceneMsgId = 9051
	SceneMsgId_SCENE_SERVERTIMEACK_ACK          SceneMsgId = 9001
	SceneMsgId_SCENE_TRANSPORTREQ_REQ           SceneMsgId = 1052
	SceneMsgId_SCENE_SWITCHSCENEREQ_REQ         SceneMsgId = 8101
)

var SceneMsgId_name = map[int32]string{
	0:    "MSG_ID",
	3101: "SCENE_ROLEJUMPREQ_REQ",
	3102: "SCENE_ROLEJUMPACK_ACK",
	1302: "SCENE_ROLEREALIVENOTIFY_NOTIFY",
	8150: "SCENE_CHANNELCHATREQ_REQ",
	8100: "SCENE_CHANNELCHATACK_ACK",
	8161: "SCENE_ACTIVITYREADYNOTIFY_NOTIFY",
	8162: "SCENE_ACTIVITYSTARTNOTIFY_NOTIFY",
	8163: "SCENE_JOINACTIVITYREQ_REQ",
	8164: "SCENE_JOINACTIVITYACK_ACK",
	8200: "SCENE_MAZEGETGEMREQ_REQ",
	9100: "SCENE_AREAINITNOTIFY_NOTIFY",
	9101: "SCENE_AREATRADENOTIFY_NOTIFY",
	9051: "SCENE_SERVERTIMEREQ_REQ",
	9001: "SCENE_SERVERTIMEACK_ACK",
	1052: "SCENE_TRANSPORTREQ_REQ",
	8101: "SCENE_SWITCHSCENEREQ_REQ",
}

var SceneMsgId_value = map[string]int32{
	"MSG_ID":                           0,
	"SCENE_ROLEJUMPREQ_REQ":            3101,
	"SCENE_ROLEJUMPACK_ACK":            3102,
	"SCENE_ROLEREALIVENOTIFY_NOTIFY":   1302,
	"SCENE_CHANNELCHATREQ_REQ":         8150,
	"SCENE_CHANNELCHATACK_ACK":         8100,
	"SCENE_ACTIVITYREADYNOTIFY_NOTIFY": 8161,
	"SCENE_ACTIVITYSTARTNOTIFY_NOTIFY": 8162,
	"SCENE_JOINACTIVITYREQ_REQ":        8163,
	"SCENE_JOINACTIVITYACK_ACK":        8164,
	"SCENE_MAZEGETGEMREQ_REQ":          8200,
	"SCENE_AREAINITNOTIFY_NOTIFY":      9100,
	"SCENE_AREATRADENOTIFY_NOTIFY":     9101,
	"SCENE_SERVERTIMEREQ_REQ":          9051,
	"SCENE_SERVERTIMEACK_ACK":          9001,
	"SCENE_TRANSPORTREQ_REQ":           1052,
	"SCENE_SWITCHSCENEREQ_REQ":         8101,
}

func (x SceneMsgId) String() string {
	return proto.EnumName(SceneMsgId_name, int32(x))
}

func (SceneMsgId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{0}
}

// 角色跳跃
type RoleJumpReq struct {
	Dir                  float32  `protobuf:"fixed32,1,opt,name=dir,proto3" json:"dir,omitempty"`
	PosX                 int32    `protobuf:"varint,2,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY                 int32    `protobuf:"varint,3,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Height               float32  `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleJumpReq) Reset()         { *m = RoleJumpReq{} }
func (m *RoleJumpReq) String() string { return proto.CompactTextString(m) }
func (*RoleJumpReq) ProtoMessage()    {}
func (*RoleJumpReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{0}
}

func (m *RoleJumpReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleJumpReq.Unmarshal(m, b)
}
func (m *RoleJumpReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleJumpReq.Marshal(b, m, deterministic)
}
func (m *RoleJumpReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleJumpReq.Merge(m, src)
}
func (m *RoleJumpReq) XXX_Size() int {
	return xxx_messageInfo_RoleJumpReq.Size(m)
}
func (m *RoleJumpReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleJumpReq.DiscardUnknown(m)
}

var xxx_messageInfo_RoleJumpReq proto.InternalMessageInfo

func (m *RoleJumpReq) GetDir() float32 {
	if m != nil {
		return m.Dir
	}
	return 0
}

func (m *RoleJumpReq) GetPosX() int32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *RoleJumpReq) GetPosY() int32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *RoleJumpReq) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

// 角色跳跃返回
type RoleJumpAck struct {
	ObjId                int32    `protobuf:"varint,1,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
	Dir                  float32  `protobuf:"fixed32,2,opt,name=dir,proto3" json:"dir,omitempty"`
	PosX                 int32    `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY                 int32    `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	Height               float32  `protobuf:"fixed32,5,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleJumpAck) Reset()         { *m = RoleJumpAck{} }
func (m *RoleJumpAck) String() string { return proto.CompactTextString(m) }
func (*RoleJumpAck) ProtoMessage()    {}
func (*RoleJumpAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{1}
}

func (m *RoleJumpAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleJumpAck.Unmarshal(m, b)
}
func (m *RoleJumpAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleJumpAck.Marshal(b, m, deterministic)
}
func (m *RoleJumpAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleJumpAck.Merge(m, src)
}
func (m *RoleJumpAck) XXX_Size() int {
	return xxx_messageInfo_RoleJumpAck.Size(m)
}
func (m *RoleJumpAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleJumpAck.DiscardUnknown(m)
}

var xxx_messageInfo_RoleJumpAck proto.InternalMessageInfo

func (m *RoleJumpAck) GetObjId() int32 {
	if m != nil {
		return m.ObjId
	}
	return 0
}

func (m *RoleJumpAck) GetDir() float32 {
	if m != nil {
		return m.Dir
	}
	return 0
}

func (m *RoleJumpAck) GetPosX() int32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *RoleJumpAck) GetPosY() int32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *RoleJumpAck) GetHeight() float32 {
	if m != nil {
		return m.Height
	}
	return 0
}

// 角色重生
type RoleReAliveNotify struct {
	ObjId                int32    `protobuf:"varint,1,opt,name=obj_id,json=objId,proto3" json:"obj_id,omitempty"`
	PosX                 float32  `protobuf:"fixed32,2,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY                 float32  `protobuf:"fixed32,3,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	PosZ                 float32  `protobuf:"fixed32,4,opt,name=pos_z,json=posZ,proto3" json:"pos_z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoleReAliveNotify) Reset()         { *m = RoleReAliveNotify{} }
func (m *RoleReAliveNotify) String() string { return proto.CompactTextString(m) }
func (*RoleReAliveNotify) ProtoMessage()    {}
func (*RoleReAliveNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{2}
}

func (m *RoleReAliveNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoleReAliveNotify.Unmarshal(m, b)
}
func (m *RoleReAliveNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoleReAliveNotify.Marshal(b, m, deterministic)
}
func (m *RoleReAliveNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoleReAliveNotify.Merge(m, src)
}
func (m *RoleReAliveNotify) XXX_Size() int {
	return xxx_messageInfo_RoleReAliveNotify.Size(m)
}
func (m *RoleReAliveNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_RoleReAliveNotify.DiscardUnknown(m)
}

var xxx_messageInfo_RoleReAliveNotify proto.InternalMessageInfo

func (m *RoleReAliveNotify) GetObjId() int32 {
	if m != nil {
		return m.ObjId
	}
	return 0
}

func (m *RoleReAliveNotify) GetPosX() float32 {
	if m != nil {
		return m.PosX
	}
	return 0
}

func (m *RoleReAliveNotify) GetPosY() float32 {
	if m != nil {
		return m.PosY
	}
	return 0
}

func (m *RoleReAliveNotify) GetPosZ() float32 {
	if m != nil {
		return m.PosZ
	}
	return 0
}

// 聊天频道请求
type ChannelChatReq struct {
	ContentType          int32    `protobuf:"varint,1,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	FromType             int32    `protobuf:"varint,2,opt,name=from_type,json=fromType,proto3" json:"from_type,omitempty"`
	ChannelType          int32    `protobuf:"varint,3,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelChatReq) Reset()         { *m = ChannelChatReq{} }
func (m *ChannelChatReq) String() string { return proto.CompactTextString(m) }
func (*ChannelChatReq) ProtoMessage()    {}
func (*ChannelChatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{3}
}

func (m *ChannelChatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelChatReq.Unmarshal(m, b)
}
func (m *ChannelChatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelChatReq.Marshal(b, m, deterministic)
}
func (m *ChannelChatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelChatReq.Merge(m, src)
}
func (m *ChannelChatReq) XXX_Size() int {
	return xxx_messageInfo_ChannelChatReq.Size(m)
}
func (m *ChannelChatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelChatReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelChatReq proto.InternalMessageInfo

func (m *ChannelChatReq) GetContentType() int32 {
	if m != nil {
		return m.ContentType
	}
	return 0
}

func (m *ChannelChatReq) GetFromType() int32 {
	if m != nil {
		return m.FromType
	}
	return 0
}

func (m *ChannelChatReq) GetChannelType() int32 {
	if m != nil {
		return m.ChannelType
	}
	return 0
}

func (m *ChannelChatReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 频道请求返回
type ChannelChatAck struct {
	FromUid              int32    `protobuf:"varint,1,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	ContentType          int32    `protobuf:"varint,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ChannelType          int32    `protobuf:"varint,5,opt,name=channel_type,json=channelType,proto3" json:"channel_type,omitempty"`
	FromType             int32    `protobuf:"varint,6,opt,name=from_type,json=fromType,proto3" json:"from_type,omitempty"`
	Content              string   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelChatAck) Reset()         { *m = ChannelChatAck{} }
func (m *ChannelChatAck) String() string { return proto.CompactTextString(m) }
func (*ChannelChatAck) ProtoMessage()    {}
func (*ChannelChatAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{4}
}

func (m *ChannelChatAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelChatAck.Unmarshal(m, b)
}
func (m *ChannelChatAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelChatAck.Marshal(b, m, deterministic)
}
func (m *ChannelChatAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelChatAck.Merge(m, src)
}
func (m *ChannelChatAck) XXX_Size() int {
	return xxx_messageInfo_ChannelChatAck.Size(m)
}
func (m *ChannelChatAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelChatAck.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelChatAck proto.InternalMessageInfo

func (m *ChannelChatAck) GetFromUid() int32 {
	if m != nil {
		return m.FromUid
	}
	return 0
}

func (m *ChannelChatAck) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChannelChatAck) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *ChannelChatAck) GetContentType() int32 {
	if m != nil {
		return m.ContentType
	}
	return 0
}

func (m *ChannelChatAck) GetChannelType() int32 {
	if m != nil {
		return m.ChannelType
	}
	return 0
}

func (m *ChannelChatAck) GetFromType() int32 {
	if m != nil {
		return m.FromType
	}
	return 0
}

func (m *ChannelChatAck) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 活动准备
type ActivityReadyNotify struct {
	ActivityId           int32    `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
	CountDown            int32    `protobuf:"varint,2,opt,name=count_down,json=countDown,proto3" json:"count_down,omitempty"`
	SwitchType           int32    `protobuf:"varint,3,opt,name=switch_type,json=switchType,proto3" json:"switch_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityReadyNotify) Reset()         { *m = ActivityReadyNotify{} }
func (m *ActivityReadyNotify) String() string { return proto.CompactTextString(m) }
func (*ActivityReadyNotify) ProtoMessage()    {}
func (*ActivityReadyNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{5}
}

func (m *ActivityReadyNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityReadyNotify.Unmarshal(m, b)
}
func (m *ActivityReadyNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityReadyNotify.Marshal(b, m, deterministic)
}
func (m *ActivityReadyNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityReadyNotify.Merge(m, src)
}
func (m *ActivityReadyNotify) XXX_Size() int {
	return xxx_messageInfo_ActivityReadyNotify.Size(m)
}
func (m *ActivityReadyNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityReadyNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityReadyNotify proto.InternalMessageInfo

func (m *ActivityReadyNotify) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *ActivityReadyNotify) GetCountDown() int32 {
	if m != nil {
		return m.CountDown
	}
	return 0
}

func (m *ActivityReadyNotify) GetSwitchType() int32 {
	if m != nil {
		return m.SwitchType
	}
	return 0
}

// 活动开始
type ActivityStartNotify struct {
	ActivityId           int32    `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
	SwitchType           int32    `protobuf:"varint,2,opt,name=switch_type,json=switchType,proto3" json:"switch_type,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	MazeSeed             int32    `protobuf:"varint,5,opt,name=maze_seed,json=mazeSeed,proto3" json:"maze_seed,omitempty"`
	TownPosX             float32  `protobuf:"fixed32,6,opt,name=town_pos_x,json=townPosX,proto3" json:"town_pos_x,omitempty"`
	TownPosY             float32  `protobuf:"fixed32,7,opt,name=town_pos_y,json=townPosY,proto3" json:"town_pos_y,omitempty"`
	TownPosZ             float32  `protobuf:"fixed32,8,opt,name=town_pos_z,json=townPosZ,proto3" json:"town_pos_z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityStartNotify) Reset()         { *m = ActivityStartNotify{} }
func (m *ActivityStartNotify) String() string { return proto.CompactTextString(m) }
func (*ActivityStartNotify) ProtoMessage()    {}
func (*ActivityStartNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{6}
}

func (m *ActivityStartNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityStartNotify.Unmarshal(m, b)
}
func (m *ActivityStartNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityStartNotify.Marshal(b, m, deterministic)
}
func (m *ActivityStartNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityStartNotify.Merge(m, src)
}
func (m *ActivityStartNotify) XXX_Size() int {
	return xxx_messageInfo_ActivityStartNotify.Size(m)
}
func (m *ActivityStartNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityStartNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityStartNotify proto.InternalMessageInfo

func (m *ActivityStartNotify) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *ActivityStartNotify) GetSwitchType() int32 {
	if m != nil {
		return m.SwitchType
	}
	return 0
}

func (m *ActivityStartNotify) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ActivityStartNotify) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ActivityStartNotify) GetMazeSeed() int32 {
	if m != nil {
		return m.MazeSeed
	}
	return 0
}

func (m *ActivityStartNotify) GetTownPosX() float32 {
	if m != nil {
		return m.TownPosX
	}
	return 0
}

func (m *ActivityStartNotify) GetTownPosY() float32 {
	if m != nil {
		return m.TownPosY
	}
	return 0
}

func (m *ActivityStartNotify) GetTownPosZ() float32 {
	if m != nil {
		return m.TownPosZ
	}
	return 0
}

// 加入活动请求
type JoinActivityReq struct {
	ActivityId           int32    `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
	JoinStatus           int32    `protobuf:"varint,2,opt,name=join_status,json=joinStatus,proto3" json:"join_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinActivityReq) Reset()         { *m = JoinActivityReq{} }
func (m *JoinActivityReq) String() string { return proto.CompactTextString(m) }
func (*JoinActivityReq) ProtoMessage()    {}
func (*JoinActivityReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{7}
}

func (m *JoinActivityReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinActivityReq.Unmarshal(m, b)
}
func (m *JoinActivityReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinActivityReq.Marshal(b, m, deterministic)
}
func (m *JoinActivityReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinActivityReq.Merge(m, src)
}
func (m *JoinActivityReq) XXX_Size() int {
	return xxx_messageInfo_JoinActivityReq.Size(m)
}
func (m *JoinActivityReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinActivityReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinActivityReq proto.InternalMessageInfo

func (m *JoinActivityReq) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *JoinActivityReq) GetJoinStatus() int32 {
	if m != nil {
		return m.JoinStatus
	}
	return 0
}

// 加入活动请求返回
type JoinActivityAck struct {
	ActivityId           int32    `protobuf:"varint,1,opt,name=activityId,proto3" json:"activityId,omitempty"`
	Errocode             int32    `protobuf:"varint,2,opt,name=errocode,proto3" json:"errocode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinActivityAck) Reset()         { *m = JoinActivityAck{} }
func (m *JoinActivityAck) String() string { return proto.CompactTextString(m) }
func (*JoinActivityAck) ProtoMessage()    {}
func (*JoinActivityAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{8}
}

func (m *JoinActivityAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinActivityAck.Unmarshal(m, b)
}
func (m *JoinActivityAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinActivityAck.Marshal(b, m, deterministic)
}
func (m *JoinActivityAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinActivityAck.Merge(m, src)
}
func (m *JoinActivityAck) XXX_Size() int {
	return xxx_messageInfo_JoinActivityAck.Size(m)
}
func (m *JoinActivityAck) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinActivityAck.DiscardUnknown(m)
}

var xxx_messageInfo_JoinActivityAck proto.InternalMessageInfo

func (m *JoinActivityAck) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *JoinActivityAck) GetErrocode() int32 {
	if m != nil {
		return m.Errocode
	}
	return 0
}

// 迷宫获取宝石请求
type MazeGetGemReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MazeGetGemReq) Reset()         { *m = MazeGetGemReq{} }
func (m *MazeGetGemReq) String() string { return proto.CompactTextString(m) }
func (*MazeGetGemReq) ProtoMessage()    {}
func (*MazeGetGemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{9}
}

func (m *MazeGetGemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MazeGetGemReq.Unmarshal(m, b)
}
func (m *MazeGetGemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MazeGetGemReq.Marshal(b, m, deterministic)
}
func (m *MazeGetGemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MazeGetGemReq.Merge(m, src)
}
func (m *MazeGetGemReq) XXX_Size() int {
	return xxx_messageInfo_MazeGetGemReq.Size(m)
}
func (m *MazeGetGemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MazeGetGemReq.DiscardUnknown(m)
}

var xxx_messageInfo_MazeGetGemReq proto.InternalMessageInfo

// 地块初始化信息
type AreaInitNotify struct {
	ErrCode              int32       `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Count                int32       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	AreaItem             []*AreaItem `protobuf:"bytes,3,rep,name=areaItem,proto3" json:"areaItem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AreaInitNotify) Reset()         { *m = AreaInitNotify{} }
func (m *AreaInitNotify) String() string { return proto.CompactTextString(m) }
func (*AreaInitNotify) ProtoMessage()    {}
func (*AreaInitNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{10}
}

func (m *AreaInitNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaInitNotify.Unmarshal(m, b)
}
func (m *AreaInitNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaInitNotify.Marshal(b, m, deterministic)
}
func (m *AreaInitNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaInitNotify.Merge(m, src)
}
func (m *AreaInitNotify) XXX_Size() int {
	return xxx_messageInfo_AreaInitNotify.Size(m)
}
func (m *AreaInitNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaInitNotify.DiscardUnknown(m)
}

var xxx_messageInfo_AreaInitNotify proto.InternalMessageInfo

func (m *AreaInitNotify) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *AreaInitNotify) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *AreaInitNotify) GetAreaItem() []*AreaItem {
	if m != nil {
		return m.AreaItem
	}
	return nil
}

// 地块信息
type AreaItem struct {
	AreaId               string   `protobuf:"bytes,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	RoleId               int32    `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserUuid             string   `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaItem) Reset()         { *m = AreaItem{} }
func (m *AreaItem) String() string { return proto.CompactTextString(m) }
func (*AreaItem) ProtoMessage()    {}
func (*AreaItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{11}
}

func (m *AreaItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaItem.Unmarshal(m, b)
}
func (m *AreaItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaItem.Marshal(b, m, deterministic)
}
func (m *AreaItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaItem.Merge(m, src)
}
func (m *AreaItem) XXX_Size() int {
	return xxx_messageInfo_AreaItem.Size(m)
}
func (m *AreaItem) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaItem.DiscardUnknown(m)
}

var xxx_messageInfo_AreaItem proto.InternalMessageInfo

func (m *AreaItem) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *AreaItem) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *AreaItem) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

// 地块交易推送
type AreaTradeNotify struct {
	AreaId               string   `protobuf:"bytes,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	RoleId               int32    `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	UserUuid             string   `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaTradeNotify) Reset()         { *m = AreaTradeNotify{} }
func (m *AreaTradeNotify) String() string { return proto.CompactTextString(m) }
func (*AreaTradeNotify) ProtoMessage()    {}
func (*AreaTradeNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{12}
}

func (m *AreaTradeNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaTradeNotify.Unmarshal(m, b)
}
func (m *AreaTradeNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaTradeNotify.Marshal(b, m, deterministic)
}
func (m *AreaTradeNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaTradeNotify.Merge(m, src)
}
func (m *AreaTradeNotify) XXX_Size() int {
	return xxx_messageInfo_AreaTradeNotify.Size(m)
}
func (m *AreaTradeNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaTradeNotify.DiscardUnknown(m)
}

var xxx_messageInfo_AreaTradeNotify proto.InternalMessageInfo

func (m *AreaTradeNotify) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *AreaTradeNotify) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *AreaTradeNotify) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

// 请求获取服务器时间
type ServerTimeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerTimeReq) Reset()         { *m = ServerTimeReq{} }
func (m *ServerTimeReq) String() string { return proto.CompactTextString(m) }
func (*ServerTimeReq) ProtoMessage()    {}
func (*ServerTimeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{13}
}

func (m *ServerTimeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerTimeReq.Unmarshal(m, b)
}
func (m *ServerTimeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerTimeReq.Marshal(b, m, deterministic)
}
func (m *ServerTimeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerTimeReq.Merge(m, src)
}
func (m *ServerTimeReq) XXX_Size() int {
	return xxx_messageInfo_ServerTimeReq.Size(m)
}
func (m *ServerTimeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerTimeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ServerTimeReq proto.InternalMessageInfo

// 服务器时间获取返回
type ServerTimeAck struct {
	ServerTime            int32    `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	ServerRealStartTime   int32    `protobuf:"varint,2,opt,name=server_real_start_time,json=serverRealStartTime,proto3" json:"server_real_start_time,omitempty"`
	OpenDays              int32    `protobuf:"varint,3,opt,name=open_days,json=openDays,proto3" json:"open_days,omitempty"`
	ServerRealCombineTime int32    `protobuf:"varint,4,opt,name=server_real_combine_time,json=serverRealCombineTime,proto3" json:"server_real_combine_time,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ServerTimeAck) Reset()         { *m = ServerTimeAck{} }
func (m *ServerTimeAck) String() string { return proto.CompactTextString(m) }
func (*ServerTimeAck) ProtoMessage()    {}
func (*ServerTimeAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{14}
}

func (m *ServerTimeAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerTimeAck.Unmarshal(m, b)
}
func (m *ServerTimeAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerTimeAck.Marshal(b, m, deterministic)
}
func (m *ServerTimeAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerTimeAck.Merge(m, src)
}
func (m *ServerTimeAck) XXX_Size() int {
	return xxx_messageInfo_ServerTimeAck.Size(m)
}
func (m *ServerTimeAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerTimeAck.DiscardUnknown(m)
}

var xxx_messageInfo_ServerTimeAck proto.InternalMessageInfo

func (m *ServerTimeAck) GetServerTime() int32 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

func (m *ServerTimeAck) GetServerRealStartTime() int32 {
	if m != nil {
		return m.ServerRealStartTime
	}
	return 0
}

func (m *ServerTimeAck) GetOpenDays() int32 {
	if m != nil {
		return m.OpenDays
	}
	return 0
}

func (m *ServerTimeAck) GetServerRealCombineTime() int32 {
	if m != nil {
		return m.ServerRealCombineTime
	}
	return 0
}

// 传送请求
type TransportReq struct {
	TransportIndex       int32    `protobuf:"varint,1,opt,name=transport_index,json=transportIndex,proto3" json:"transport_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransportReq) Reset()         { *m = TransportReq{} }
func (m *TransportReq) String() string { return proto.CompactTextString(m) }
func (*TransportReq) ProtoMessage()    {}
func (*TransportReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{15}
}

func (m *TransportReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportReq.Unmarshal(m, b)
}
func (m *TransportReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportReq.Marshal(b, m, deterministic)
}
func (m *TransportReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportReq.Merge(m, src)
}
func (m *TransportReq) XXX_Size() int {
	return xxx_messageInfo_TransportReq.Size(m)
}
func (m *TransportReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportReq.DiscardUnknown(m)
}

var xxx_messageInfo_TransportReq proto.InternalMessageInfo

func (m *TransportReq) GetTransportIndex() int32 {
	if m != nil {
		return m.TransportIndex
	}
	return 0
}

// 切换场景请求
type SwitchSceneReq struct {
	SceneId              int32    `protobuf:"varint,1,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchSceneReq) Reset()         { *m = SwitchSceneReq{} }
func (m *SwitchSceneReq) String() string { return proto.CompactTextString(m) }
func (*SwitchSceneReq) ProtoMessage()    {}
func (*SwitchSceneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5bd834e1feb3b48, []int{16}
}

func (m *SwitchSceneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchSceneReq.Unmarshal(m, b)
}
func (m *SwitchSceneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchSceneReq.Marshal(b, m, deterministic)
}
func (m *SwitchSceneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchSceneReq.Merge(m, src)
}
func (m *SwitchSceneReq) XXX_Size() int {
	return xxx_messageInfo_SwitchSceneReq.Size(m)
}
func (m *SwitchSceneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchSceneReq.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchSceneReq proto.InternalMessageInfo

func (m *SwitchSceneReq) GetSceneId() int32 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func init() {
	proto.RegisterEnum("SceneMsgId", SceneMsgId_name, SceneMsgId_value)
	proto.RegisterType((*RoleJumpReq)(nil), "RoleJumpReq")
	proto.RegisterType((*RoleJumpAck)(nil), "RoleJumpAck")
	proto.RegisterType((*RoleReAliveNotify)(nil), "RoleReAliveNotify")
	proto.RegisterType((*ChannelChatReq)(nil), "ChannelChatReq")
	proto.RegisterType((*ChannelChatAck)(nil), "ChannelChatAck")
	proto.RegisterType((*ActivityReadyNotify)(nil), "ActivityReadyNotify")
	proto.RegisterType((*ActivityStartNotify)(nil), "ActivityStartNotify")
	proto.RegisterType((*JoinActivityReq)(nil), "JoinActivityReq")
	proto.RegisterType((*JoinActivityAck)(nil), "JoinActivityAck")
	proto.RegisterType((*MazeGetGemReq)(nil), "MazeGetGemReq")
	proto.RegisterType((*AreaInitNotify)(nil), "AreaInitNotify")
	proto.RegisterType((*AreaItem)(nil), "AreaItem")
	proto.RegisterType((*AreaTradeNotify)(nil), "AreaTradeNotify")
	proto.RegisterType((*ServerTimeReq)(nil), "ServerTimeReq")
	proto.RegisterType((*ServerTimeAck)(nil), "ServerTimeAck")
	proto.RegisterType((*TransportReq)(nil), "TransportReq")
	proto.RegisterType((*SwitchSceneReq)(nil), "SwitchSceneReq")
}

func init() { proto.RegisterFile("scene.proto", fileDescriptor_d5bd834e1feb3b48) }

var fileDescriptor_d5bd834e1feb3b48 = []byte{
	// 1064 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x56, 0xdb, 0x46,
	0x14, 0xae, 0xff, 0xe5, 0x4b, 0x02, 0x74, 0x52, 0x88, 0xf8, 0x09, 0x25, 0xea, 0xc9, 0x29, 0xa7,
	0x3d, 0x27, 0x8b, 0x66, 0x91, 0x25, 0xd5, 0x11, 0xc2, 0x88, 0x60, 0x43, 0x46, 0x82, 0xd6, 0x6c,
	0x54, 0x61, 0x4d, 0xb0, 0xa8, 0xad, 0x31, 0xd2, 0x18, 0x30, 0x4f, 0xd0, 0x45, 0xb3, 0xed, 0x2a,
	0xed, 0xaa, 0x5d, 0xf4, 0x19, 0xfa, 0x1e, 0xd9, 0x74, 0xd5, 0x9f, 0x17, 0xe8, 0x1b, 0xf4, 0xcc,
	0x8c, 0x64, 0x59, 0xc6, 0x39, 0xcd, 0xa2, 0x2b, 0xeb, 0x7e, 0xdf, 0x9d, 0xfb, 0xdd, 0x7b, 0xe7,
	0x5e, 0xc9, 0x30, 0x17, 0x77, 0x48, 0x48, 0x9e, 0x0e, 0x22, 0xca, 0xa8, 0xe6, 0xc1, 0x1c, 0xa6,
	0x3d, 0xb2, 0x3f, 0xec, 0x0f, 0x30, 0xb9, 0x44, 0x8b, 0x50, 0xf2, 0x83, 0x48, 0x2d, 0x6c, 0x16,
	0xb6, 0x8a, 0x98, 0x3f, 0xa2, 0x07, 0x50, 0x19, 0xd0, 0xd8, 0xbd, 0x51, 0x8b, 0x9b, 0x85, 0xad,
	0x0a, 0x2e, 0x0f, 0x68, 0xfc, 0x75, 0x0a, 0x8e, 0xd4, 0xd2, 0x18, 0x6c, 0xa3, 0x65, 0xa8, 0x76,
	0x49, 0x70, 0xde, 0x65, 0x6a, 0x59, 0x1c, 0x4f, 0x2c, 0xed, 0x26, 0x93, 0xd0, 0x3b, 0xdf, 0xa2,
	0x25, 0xa8, 0xd2, 0xb3, 0x0b, 0x37, 0xf0, 0x85, 0x4a, 0x05, 0x57, 0xe8, 0xd9, 0x85, 0xe5, 0xa7,
	0xca, 0xc5, 0x19, 0xca, 0xa5, 0x59, 0xca, 0xe5, 0x99, 0xca, 0x95, 0x9c, 0x72, 0x00, 0x1f, 0x72,
	0x65, 0x4c, 0xf4, 0x5e, 0x70, 0x45, 0x5a, 0x94, 0x05, 0xaf, 0x46, 0xef, 0xd2, 0xcf, 0xd5, 0x59,
	0x9c, 0x55, 0x67, 0x31, 0x51, 0x4b, 0xc0, 0xdb, 0xa4, 0x4c, 0x0e, 0x9e, 0x6a, 0xaf, 0x0b, 0x30,
	0x6f, 0x74, 0xbd, 0x30, 0x24, 0x3d, 0xa3, 0xeb, 0x31, 0xde, 0xcb, 0xc7, 0x70, 0xaf, 0x43, 0x43,
	0x46, 0x42, 0xe6, 0xb2, 0xd1, 0x80, 0x24, 0x72, 0x73, 0x09, 0xe6, 0x8c, 0x06, 0x04, 0xad, 0x41,
	0xfd, 0x55, 0x44, 0xfb, 0x92, 0x97, 0x0d, 0x56, 0x38, 0x20, 0x48, 0x7e, 0x5e, 0x46, 0x94, 0x7c,
	0x29, 0x39, 0x2f, 0x31, 0xe1, 0xa2, 0x42, 0x2d, 0x09, 0x27, 0x92, 0xa9, 0xe3, 0xd4, 0xd4, 0xde,
	0xe6, 0xf3, 0xe1, 0x8d, 0x5f, 0x01, 0x11, 0xdb, 0x1d, 0x8e, 0x4b, 0xaf, 0x71, 0xfb, 0x38, 0xf0,
	0xd1, 0x2a, 0x28, 0xc3, 0x98, 0x44, 0xa1, 0xd7, 0x97, 0x69, 0xd4, 0xf1, 0xd8, 0xe6, 0x17, 0x13,
	0x93, 0xf4, 0x12, 0xf8, 0xe3, 0x9d, 0xc2, 0xca, 0x77, 0x0b, 0x9b, 0xce, 0xbd, 0x72, 0x37, 0xf7,
	0x5c, 0xed, 0xd5, 0xa9, 0xda, 0x27, 0x0a, 0xab, 0xe5, 0x0b, 0x1b, 0xc2, 0x03, 0xbd, 0xc3, 0x82,
	0xab, 0x80, 0x8d, 0x30, 0xf1, 0xfc, 0x51, 0x72, 0xab, 0x1b, 0x00, 0x5e, 0x02, 0x5b, 0x69, 0x79,
	0x13, 0x08, 0x7a, 0x04, 0xd0, 0xa1, 0xc3, 0x90, 0xb9, 0x3e, 0xbd, 0x0e, 0x93, 0x56, 0xd7, 0x05,
	0xb2, 0x43, 0xaf, 0x43, 0xf4, 0x31, 0xcc, 0xc5, 0xd7, 0x01, 0xeb, 0x74, 0x27, 0x5b, 0x0d, 0x12,
	0xe2, 0x09, 0x69, 0xff, 0x14, 0x32, 0x5d, 0x9b, 0x79, 0x11, 0x7b, 0x4f, 0xdd, 0xa9, 0xc0, 0xc5,
	0xe9, 0xc0, 0x68, 0x1e, 0x8a, 0xd6, 0x40, 0x08, 0xd6, 0x71, 0xd1, 0x1a, 0x20, 0x04, 0xe5, 0x01,
	0x8d, 0x58, 0x36, 0xdf, 0x11, 0xe3, 0xad, 0xea, 0x7b, 0xb7, 0xc4, 0x8d, 0x09, 0xf1, 0x93, 0x56,
	0x2a, 0x1c, 0xb0, 0x09, 0xf1, 0xd1, 0x3a, 0x00, 0xa3, 0xd7, 0xa1, 0x2b, 0xa7, 0xb7, 0x2a, 0x66,
	0x52, 0xe1, 0xc8, 0x11, 0x9f, 0xe0, 0x49, 0x76, 0x24, 0x7a, 0x99, 0xb1, 0xed, 0x1c, 0x7b, 0xab,
	0x2a, 0x39, 0xf6, 0x54, 0xc3, 0xb0, 0xb0, 0x4f, 0x83, 0x30, 0x6b, 0xf7, 0xe5, 0xfb, 0x94, 0x7b,
	0x41, 0x83, 0xd0, 0x8d, 0x99, 0xc7, 0x86, 0x71, 0x5a, 0x2e, 0x87, 0x6c, 0x81, 0x68, 0xcd, 0x7c,
	0x4c, 0x3e, 0x97, 0xff, 0x15, 0x73, 0x15, 0x14, 0x12, 0x45, 0xb4, 0x43, 0xfd, 0xf1, 0x8e, 0xa4,
	0xb6, 0xb6, 0x00, 0xf7, 0x9b, 0xde, 0x2d, 0x69, 0x10, 0xd6, 0x20, 0x7d, 0x4c, 0x2e, 0xb5, 0x73,
	0x98, 0xd7, 0x23, 0xe2, 0x59, 0x61, 0x90, 0xde, 0x90, 0x0a, 0x35, 0x12, 0x45, 0x06, 0x3f, 0x9d,
	0x4c, 0x7d, 0x62, 0xa2, 0x8f, 0xa0, 0x22, 0x26, 0x20, 0x89, 0x2a, 0x0d, 0xf4, 0x04, 0x14, 0x8f,
	0x47, 0x60, 0xa4, 0xaf, 0x96, 0x36, 0x4b, 0x5b, 0x73, 0x5f, 0xd4, 0x9f, 0xea, 0x09, 0x80, 0xc7,
	0x94, 0xd6, 0x06, 0x25, 0x45, 0xd1, 0x43, 0xa8, 0x71, 0x3c, 0x7d, 0xa7, 0xd4, 0x71, 0x55, 0xb8,
	0xf9, 0x9c, 0x88, 0x68, 0x8f, 0x70, 0x42, 0x6a, 0x54, 0xb9, 0x69, 0xf9, 0xfc, 0x46, 0xf9, 0x82,
	0xb9, 0x43, 0xbe, 0x8c, 0xa5, 0x6c, 0xe3, 0x8e, 0x87, 0x81, 0xaf, 0x7d, 0x03, 0x0b, 0x3c, 0xb4,
	0x13, 0x79, 0x7e, 0xfa, 0xd2, 0xfa, 0x9f, 0x15, 0x16, 0xe0, 0xbe, 0x4d, 0xa2, 0x2b, 0x12, 0x39,
	0x41, 0x9f, 0xf0, 0xb6, 0xfd, 0x56, 0x98, 0x44, 0xf8, 0xad, 0xf0, 0xc1, 0x15, 0x80, 0xcb, 0x82,
	0x7e, 0xda, 0x3a, 0x88, 0xc7, 0x3e, 0xe8, 0x19, 0x2c, 0x27, 0x0e, 0x11, 0xf1, 0x7a, 0xfc, 0xc6,
	0x23, 0x26, 0x7d, 0x65, 0x22, 0x0f, 0x24, 0x8b, 0x89, 0xd7, 0x13, 0x0b, 0x23, 0x0e, 0xad, 0x41,
	0x9d, 0x0e, 0x48, 0xe8, 0xfa, 0xde, 0x28, 0x4e, 0xb6, 0x4c, 0xe1, 0xc0, 0x8e, 0x37, 0x8a, 0xd1,
	0x73, 0x50, 0x27, 0x23, 0x76, 0x68, 0xff, 0x2c, 0x08, 0x89, 0x8c, 0x29, 0xd7, 0x61, 0x29, 0x8b,
	0x69, 0x48, 0x96, 0x47, 0xd5, 0x9e, 0xc3, 0x3d, 0x27, 0xf2, 0xc2, 0x98, 0x2f, 0x0b, 0x9f, 0xd2,
	0x4f, 0x61, 0x81, 0xa5, 0xb6, 0x1b, 0x84, 0x3e, 0xb9, 0x49, 0xf2, 0x9f, 0x1f, 0xc3, 0x16, 0x47,
	0xb5, 0xcf, 0x61, 0xde, 0x16, 0xab, 0x68, 0xf3, 0x4f, 0x22, 0x3f, 0xba, 0x02, 0x8a, 0xf8, 0x3c,
	0x66, 0xdf, 0x87, 0x9a, 0xb0, 0x2d, 0xff, 0xb3, 0x37, 0x65, 0x00, 0xe1, 0xd7, 0x8c, 0xcf, 0x2d,
	0x1f, 0x01, 0x54, 0x9b, 0x76, 0xc3, 0xb5, 0x76, 0x16, 0x3f, 0x40, 0xab, 0xb0, 0x64, 0x1b, 0x66,
	0xcb, 0x74, 0xf1, 0xe1, 0x81, 0xb9, 0x7f, 0xdc, 0x3c, 0xc2, 0xe6, 0x4b, 0x17, 0x9b, 0x2f, 0x17,
	0x7f, 0x54, 0xef, 0x72, 0xba, 0xf1, 0xc2, 0xd5, 0x8d, 0x17, 0x8b, 0x3f, 0xa9, 0xe8, 0x13, 0xd8,
	0xc8, 0x38, 0x6c, 0xea, 0x07, 0xd6, 0x89, 0xd9, 0x3a, 0x74, 0xac, 0xdd, 0xb6, 0x2b, 0x7f, 0x16,
	0x7f, 0x00, 0xf4, 0x08, 0x54, 0xe9, 0x64, 0xec, 0xe9, 0xad, 0x96, 0x79, 0x60, 0xec, 0xe9, 0x4e,
	0x1a, 0xff, 0xed, 0xf6, 0x4c, 0x3a, 0x95, 0xf8, 0x79, 0x1b, 0x3d, 0x81, 0x4d, 0x49, 0xeb, 0x86,
	0x63, 0x9d, 0x58, 0x4e, 0x1b, 0x9b, 0xfa, 0x4e, 0x3b, 0x2f, 0xf2, 0xc7, 0x0c, 0x37, 0xdb, 0xd1,
	0xb1, 0x93, 0x77, 0xfb, 0x73, 0x1b, 0x6d, 0xc0, 0x8a, 0x74, 0xdb, 0x3f, 0xb4, 0x5a, 0x59, 0x44,
	0x99, 0xcc, 0x5f, 0xef, 0xe0, 0xd3, 0x6c, 0xfe, 0xde, 0x46, 0xeb, 0xf0, 0x50, 0xf2, 0x4d, 0xfd,
	0xd4, 0x6c, 0x98, 0x4e, 0xc3, 0x6c, 0xa6, 0xa7, 0xbf, 0xfb, 0x12, 0x6d, 0xc2, 0x5a, 0x92, 0x04,
	0x36, 0x75, 0xab, 0x65, 0x4d, 0xe9, 0x7f, 0xdf, 0x40, 0x8f, 0x61, 0x3d, 0xf3, 0x70, 0xb0, 0xbe,
	0x33, 0xd5, 0xae, 0xd7, 0x8d, 0x4c, 0xc2, 0x36, 0xf1, 0x89, 0x89, 0x1d, 0xab, 0x69, 0xa6, 0x12,
	0xbf, 0xef, 0xce, 0x62, 0xd3, 0xf4, 0x7e, 0xdd, 0x45, 0x6b, 0xb0, 0x2c, 0x59, 0x07, 0xeb, 0x2d,
	0xfb, 0xe8, 0x10, 0x8f, 0x1b, 0xfd, 0x46, 0xc9, 0x1a, 0x6d, 0x7f, 0x65, 0x39, 0xc6, 0x9e, 0x78,
	0x4e, 0xe9, 0x5f, 0xb6, 0xcf, 0xaa, 0xe2, 0x0f, 0xd5, 0xb3, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0x18, 0x56, 0x33, 0x5f, 0x09, 0x00, 0x00,
}
